### PR TITLE
Mistral: map toolCallId for tool messages

### PR DESCRIPTION
**Pull request by ghost**
## Change
Mistral tests are currently fail because all of a sudden Mistral decided to make `tool_call_id` parameter in `tool` messages mandatory:
`Runtime java.lang.RuntimeException: status code: 400; body: {"object":"error","message":"Tool call id has to be defined.","type":"invalid_request_error","param":null,"code":null}`.

This probably affects all Mistral users using tools.

cc @geoand 

## General checklist
- [X] There are no breaking changes
- [ ] I have added unit and/or integration tests for my change
- [ ] The tests cover both positive and negative cases
- [X] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [ ] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green
- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

### CODE REVIEW

**Comment by langchain4j** [comment]
cc @katcharov, this is an example of an issue that would not be caught with mocked LLM responses

**Comment by geoand** [comment]
Thanks a lot for the heads up!

**Comment by czelabueno** [comment]
hey @langchain4j your changes are enough to fix the issue, however this change for tool messages have introduced also a new `MistralAiToolChoiceName` enum called `required` which is pending to add. This new enum is not strictly related to the tool messages requests but would be great to complete with all changes involved in tool messages
We would need change `ANY` by `REQUIRED` here:

https://github.com/langchain4j/langchain4j/blob/9b63e2ccdf76b8014699498af39ca8bcf81cc009/langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/MistralAiChatModel.java#L163

and here:

https://github.com/langchain4j/langchain4j/blob/9b63e2ccdf76b8014699498af39ca8bcf81cc009/langchain4j-mistral-ai/src/main/java/dev/langchain4j/model/mistralai/MistralAiStreamingChatModel.java#L156

We can handle it in other PR if you prefer it like this. WDYT?

**Comment by langchain4j** [comment]
@czelabueno oh, good to know! I guess tool choice logic can be added after https://github.com/langchain4j/langchain4j/pull/1989 is merged (I plan to merge tomorrow). https://github.com/langchain4j/langchain4j/pull/1989 introduces model-agnostic `ToolChoice`, so I guess it makes sense to wait till then?

**Comment by langchain4j** [comment]
BTW did Mistral announce this **_breaking_** change? I did not get any email notification

**Comment by czelabueno** [comment]
@langchain4j about below

> @czelabueno oh, good to know! I guess tool choice logic can be added after https://github.com/langchain4j/langchain4j/pull/1989 is merged (I plan to merge tomorrow). https://github.com/langchain4j/langchain4j/pull/1989 introduces model-agnostic ToolChoice, so I guess it makes sense to wait till then?

ok make perfect sense to me, in fact the new `ChatParameters` fit well with the current MistralAI API specs, if it will be abstracted would be great!

**Comment by czelabueno** [comment]
@langchain4j 

> BTW did Mistral announce this breaking change? I did not get any email notification

in fact it was changed from May 24 😅, but I think that due to recent API changes, the API validation is well working now, for their official SDK it's mandatory as well.
This is my bad because I was away for a few months but I'm already active again to update all the changes 🙂
 
image

**Comment by langchain4j** [comment]
@czelabueno ah, I see! But in any case I would expect them to send the "final warning" email before actually making it mandatory. I can imagine there are still a lot of applicaitons that do not send the id and were broken by this change

**Pull request merged**
