### PR TITLE
PgVectorEmbeddingStore: remove by ID

### PR DESCRIPTION
**Pull request by nottyjay**
## Change
Add search method in PgVectorEmbeddingStore
Add remove data method in the interface of EmbeddingStore
Add remove data method in PgVectorEmbeddingStore

## Checklist
- [x] I have added unit and integration tests for my change
- [x] All unit and integration tests in the module I have added/changed are green
- [x] All unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules are green

## Checklist for adding new embedding store integration
- [x] I have added a {NameOfIntegration}EmbeddingStoreIT that extends from either EmbeddingStoreIT or EmbeddingStoreWithFilteringIT

### CODE REVIEW

**Comment by nottyjay** [comment]
@langchain4j 
Add remove method to delete embedding data which stored in vector store. 
Add search in PgVectorEmbeddingStore
I checked locally everything compiles and tests pass.

**Comment by langchain4j** [comment]
@nottyjay thanks a lot!
Please revert changes of formatting, it is imposible to review right now :(

**Comment by langchain4j** [comment]
Related issue: https://github.com/langchain4j/langchain4j/issues/301

**Comment by humcqc** [comment]
Hi @langchain4j , @nottyjay perhaps this should be done after https://github.com/langchain4j/langchain4j/pull/851 to avoid more conflicts. 
@nottyjay perhaps you could implement it on top of this PR, or I can do it quickly after we merge #851

**Comment by langchain4j** [comment]
Closing thi since https://github.com/langchain4j/langchain4j/pull/1113 has been released

**Pull request closed without merging**
