### PR TITLE
Image tests and docs.

### PR DESCRIPTION
**Pull request by crutcher**
Add ImageTest, to bring coverage to 100%.

### CODE REVIEW

**Review by Heezer — APPROVED** [review]
looks like auto generated tests, but fine 😄

**Comment by crutcher** [comment]
@Heezer they're not autogenerated; I spun up code coverage, made a list of all the missing coverage in the current project, and worked my way through the majority langchain4j-core.

I'm a big fan of full-coverage, because it means we can apply aggressive refactoring to libraries when needed, and be confident in the results.

I still need someone to submit this PR; I don't have submit power, even with an Approval

**Comment by Heezer** [comment]
check the failing tests, I'm not sure where it is due to your code or mess in master

**Comment by Heezer** [comment]
works now after fixes on master, I've just merged

**Pull request merged**
