### PR TITLE
Add null check when converting properties to openAIProperties

### LINKED ISSUE #1837: [BUG] java.lang.NullPointerException: Cannot invoke "java.util.Map.forEach(java.util.function.BiConsumer)" because "properties" is null
**Describe the bug**
I got a null pointer exception from the InternalOpenAIHelper->toOpenAIProperties method after updating to the latest version of LangChain4j (as part of the Quarkus LangChain4j extension). The NPE was somehow caused by an unused parameter in a Tool declaration, which set an empty property value . You can see the commit that removed this parameter here: https://github.com/kdubois/quarkus-langchain4j-samples/commit/04fdab776e66b04431dd39793cde6039a6dbb3a7.  

While this commit fixed my code, I believe there should be a null check in the InternalOpenAIHelper class to avoid this issue. Or at least the NPE should be caught with a more explicit error message since it was quite unclear why I got the error in the first place. 

**Log and Stack trace**
2024-09-26 11:21:22,735 ERROR [com.red.dev.ChatSocket] (vert.x-worker-thread-1) Error calling the LLM

Exception in ChatSocket.java:25
           23      public String onMessage(String userMessage){
           24          try {
        -> 25              return assistant.chat(userMessage);
           26          } catch (Exception e) {
           27              Log.error("Error calling the LLM", e);

: java.lang.NullPointerException: Cannot invoke "java.util.Map.forEach(java.util.function.BiConsumer)" because "properties" is null
        at dev.langchain4j.model.openai.InternalOpenAiHelper.toOpenAiProperties(InternalOpenAiHelper.java:262)
        at dev.langchain4j.model.openai.InternalOpenAiHelper.toOpenAiJsonSchemaElement(InternalOpenAiHelper.java:275)
        at dev.langchain4j.model.openai.InternalOpenAiHelper.lambda$toOpenAiProperties$2(InternalOpenAiHelper.java:263)
        at java.base/java.util.HashMap.forEach(HashMap.java:1429)
        at dev.langchain4j.model.openai.InternalOpenAiHelper.toOpenAiProperties(InternalOpenAiHelper.java:262)
        at dev.langchain4j.model.openai.InternalOpenAiHelper.toOpenAiParameters(InternalOpenAiHelper.java:246)
        at dev.langchain4j.model.openai.InternalOpenAiHelper.toTool(InternalOpenAiHelper.java:204)
        at dev.langchain4j.model.openai.InternalOpenAiHelper.lambda$toTools$1(InternalOpenAiHelper.java:196)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at dev.langchain4j.model.openai.InternalOpenAiHelper.toTools(InternalOpenAiHelper.java:197)
        at dev.langchain4j.model.openai.OpenAiChatModel.generate(OpenAiChatModel.java:226)
        at dev.langchain4j.model.openai.OpenAiChatModel.generate(OpenAiChatModel.java:176)
        at dev.langchain4j.model.chat.ChatLanguageModel_XNMsOaekknG7BdNZ5YSUkjh1SqE_Synthetic_ClientProxy.generate(Unknown Source)
        at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.doImplement(AiServiceMethodImplementationSupport.java:238)
        at io.quarkiverse.langchain4j.runtime.aiservice.AiServiceMethodImplementationSupport.implement(AiServiceMethodImplementationSupport.java:110)
        at io.quarkiverse.langchain4j.runtime.aiservice.MethodImplementationSupportProducer$1$1.apply(MethodImplementationSupportProducer.java:31)
        at io.quarkiverse.langchain4j.runtime.aiservice.MethodImplementationSupportProducer$1$1.apply(MethodImplementationSupportProducer.java:28)
        at io.quarkiverse.langchain4j.runtime.aiservice.MetricsCountedWrapper.wrap(MetricsCountedWrapper.java:22)
        at io.quarkiverse.langchain4j.runtime.aiservice.MethodImplementationSupportProducer$1$2.apply(MethodImplementationSupportProducer.java:40)
        at io.quarkiverse.langchain4j.runtime.aiservice.MethodImplementationSupportProducer$1$2.apply(MethodImplementationSupportProducer.java:37)
        at io.quarkiverse.langchain4j.runtime.aiservice.MetricsTimedWrapper$2.get(MetricsTimedWrapper.java:42)
        at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:69)
        at io.quarkiverse.langchain4j.runtime.aiservice.MetricsTimedWrapper.wrap(MetricsTimedWrapper.java:39)
        at io.quarkiverse.langchain4j.runtime.aiservice.MethodImplementationSupportProducer$1$2.apply(MethodImplementationSupportProducer.java:40)
        at io.quarkiverse.langchain4j.runtime.aiservice.MethodImplementationSupportProducer$1$2.apply(MethodImplementationSupportProducer.java:37)
        at io.quarkiverse.langchain4j.runtime.aiservice.SpanWrapper.wrap(SpanWrapper.java:32)
        at io.quarkiverse.langchain4j.runtime.aiservice.MethodImplementationSupportProducer$1$2.apply(MethodImplementationSupportProducer.java:40)
        at io.quarkiverse.langchain4j.runtime.aiservice.MethodImplementationSupportProducer$1$2.apply(MethodImplementationSupportProducer.java:37)
        at io.quarkiverse.langchain4j.runtime.aiservice.MethodImplementationSupportProducer$1.implement(MethodImplementationSupportProducer.java:46)
        at com.redhat.developers.AssistantForCustomerSupport$$QuarkusImpl.chat(Unknown Source)
        at com.redhat.developers.AssistantForCustomerSupport$$QuarkusImpl_ClientProxy.chat(Unknown Source)
        at com.redhat.developers.ChatSocket.onMessage(ChatSocket.java:25)
        at com.redhat.developers.ChatSocket_WebSocketServerEndpoint.doOnTextMessage(Unknown Source)
        at io.quarkus.websockets.next.runtime.WebSocketEndpointBase$4.call(WebSocketEndpointBase.java:158)
        at io.quarkus.websockets.next.runtime.WebSocketEndpointBase$4.call(WebSocketEndpointBase.java:152)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$0(ContextImpl.java:178)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270)
        at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:210)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)

**To Reproduce**
Check out this commit version of the repo:
https://github.com/kdubois/quarkus-langchain4j-samples/tree/7058bc36e8ca6baad21a8468d85321e977dbfada

Then start it up (eg. ./mvnw quarkus:dev) and then go to http://localhost:8080/chat-assistant.html and insert a message in the chat box. You will now see the NPE.

**Expected behavior**
The NPE should be handled more gracefully.

**Please complete the following information:**
- LangChain4j version: 0.34
- LLM(s) used: OpenAI gpt4o
- Java version: 21.0.4-tem
- Quarkus LangChain4j version: 0.18

**Additional context**

### PR DESCRIPTION
**Pull request by kdubois**
## Issue

Fixes #1837

## Change

Put a simple null check to avoid a NPE.  I believe this is all that's needed, but LMK if it should instead bubble up a more explicit exception.

I did not create a new test. There's very little code coverage for any of the methods in this class & TBH I wasn't sure where to even begin :smile: .  Feel free to point me in the right direction if you'd like me to create a new test 

## General checklist

- [ x ] There are no breaking changes
- [ ] I have added unit and integration tests for my change
- [ x ] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [ x ] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for adding new model integration

- [ ] I have added my new module in the [BOM](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-bom/pom.xml)

## Checklist for adding new embedding store integration

- [ ] I have added a `{NameOfIntegration}EmbeddingStoreIT` that extends from either `EmbeddingStoreIT` or `EmbeddingStoreWithFilteringIT`
- [ ] I have added my new module in the [BOM](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-bom/pom.xml)

## Checklist for changing existing embedding store integration

- [ ] I have manually verified that the `{NameOfIntegration}EmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

### CODE REVIEW

**Comment by langchain4j** [comment]
@kdubois thank you!

I am not sure that simple null check will help though.
It seems that the problem is deeper and is related to the `LocalDate` type and how we create a JSON schema for it.

Here is how properties for `LocalDate` parameter look like in (vanilla) LangChain4j:
image

I suspect that Quarkus LangChain4j handles this differently. `ToolProcessor` in Quarkus LangChain4j uses old outdated code to handle objects:

> return removeNulls(OBJECT, description); // TODO provide internals

This is why it does not include `properties`. NPE happens later when mapping from LC4j tool model to OpenAI tool model.
I guess Quarkus LC4j should sync/reuse code that creates JSON schema for tools, although it probably makes sense to wait till https://github.com/langchain4j/langchain4j/pull/1668 is finalized and merged (should be included in the upcoming release in a few weeks) to avoid re-implementing this twice.

cc @geoand

**Comment by geoand** [comment]
Thanks for the ping @langchain4j

**Comment by langchain4j** [comment]
Should we close this PR?

**Comment by geoand** [comment]
👍🏽

**Pull request closed without merging**
