### PR TITLE
Fix #444: Added missing GraalVM metadata for Gson and excluded commons-logging

### LINKED ISSUE #444: [BUG] Native Java Image with GraalVM fails when calling generate using VertexAiChatModel
A Java 21 application, using Langchain4j 0.25, Vision API, Vertex Text and Vertex Chat is containerized and deployed to Google Cloud Run. 

The regular JIT image deploys and runs without any problem. The native Java image, built using GraalVM, can be started, calls to Google Vision API (no Langchain4j usage) are successful, while the call to VertexAIChatModel(with Langchain4j) encounters a failure.

**Describe the bug**
Assumption is that it fails due to a reflection call and missing GraalVM metadata.
Second assumption is that Langchain4j uses okHTTP3 4.1.0, and the support for native is listed as available in 5.0 alpha2

**Log and Stack trace**
The failure is captured in this stacktrace:
```
com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Invalid instance. Missing required messages field. 
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:92) ~[na:na]
	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:41) ~[na:na]
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:86) ~[na:na]
	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66) ~[na:na]
	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97) ~[na:na]
	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:84) ~[na:na]
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1127) ~[na:na]
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31) ~[services.ImageAnalysisApplication:na]
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1286) ~[services.ImageAnalysisApplication:na]
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1055) ~[services.ImageAnalysisApplication:na]
	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:807) ~[services.ImageAnalysisApplication:na]
	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:568) ~[na:na]
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:538) ~[na:na]
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[services.ImageAnalysisApplication:1.59.1]
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[services.ImageAnalysisApplication:1.59.1]
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[services.ImageAnalysisApplication:1.59.1]
	at com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:570) ~[na:na]
	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:489) ~[na:na]
	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:453) ~[na:na]
	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:486) ~[na:na]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574) ~[na:na]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72) ~[na:na]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742) ~[na:na]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723) ~[na:na]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[services.ImageAnalysisApplication:1.59.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[services.ImageAnalysisApplication:1.59.1]
	at java.base@21.0.1/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[services.ImageAnalysisApplication:na]
	at java.base@21.0.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base@21.0.1/java.lang.Thread.runWith(Thread.java:1596) ~[services.ImageAnalysisApplication:na]
	at java.base@21.0.1/java.lang.Thread.run(Thread.java:1583) ~[services.ImageAnalysisApplication:na]
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:837) ~[services.ImageAnalysisApplication:na]
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211) ~[na:na]
	Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57) ~[na:na]
		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112) ~[services.ImageAnalysisApplication:2.38.0]
		at com.google.cloud.aiplatform.v1.PredictionServiceClient.predict(PredictionServiceClient.java:307) ~[na:na]
		at com.google.cloud.aiplatform.v1.PredictionServiceClient.predict(PredictionServiceClient.java:225) ~[na:na]
		at dev.langchain4j.model.vertexai.VertexAiChatModel.lambda$generate$0(VertexAiChatModel.java:84) ~[na:na]
		at dev.langchain4j.internal.RetryUtils.withRetry(RetryUtils.java:26) ~[na:na]
		at dev.langchain4j.model.vertexai.VertexAiChatModel.generate(VertexAiChatModel.java:84) ~[na:na]
		at dev.langchain4j.model.chat.ChatLanguageModel.generate(ChatLanguageModel.java:39) ~[services.ImageAnalysisApplication:na]
		at services.EventController.receiveMessage(EventController.java:265) ~[services.ImageAnalysisApplication:na]
		at java.base@21.0.1/java.lang.reflect.Method.invoke(Method.java:580) ~[services.ImageAnalysisApplication:na]
		at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:262) ~[services.ImageAnalysisApplication:6.1.2]
		at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:190) ~[services.ImageAnalysisApplication:6.1.2]
		at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[services.ImageAnalysisApplication:6.1.2]
		at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:917) ~[services.ImageAnalysisApplication:6.1.2]
		at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:829) ~[services.ImageAnalysisApplication:6.1.2]
		at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[services.ImageAnalysisApplication:6.1.2]
		at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089) ~[services.ImageAnalysisApplication:6.1.2]
		at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979) ~[services.ImageAnalysisApplication:6.1.2]
		at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[services.ImageAnalysisApplication:6.1.2]
		at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914) ~[services.ImageAnalysisApplication:6.1.2]
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590) ~[services.ImageAnalysisApplication:6.0]
		at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[services.ImageAnalysisApplication:6.1.2]
		at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[services.ImageAnalysisApplication:6.0]
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[na:na]
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[na:na]
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[services.ImageAnalysisApplication:10.1.17]
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[na:na]
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[na:na]
		at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[services.ImageAnalysisApplication:6.1.2]
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[services.ImageAnalysisApplication:6.1.2]
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[na:na]
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[na:na]
		at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[services.ImageAnalysisApplication:6.1.2]
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[services.ImageAnalysisApplication:6.1.2]
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[na:na]
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[na:na]
		at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109) ~[services.ImageAnalysisApplication:6.1.2]
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[services.ImageAnalysisApplication:6.1.2]
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[na:na]
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[na:na]
		at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[services.ImageAnalysisApplication:6.1.2]
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[services.ImageAnalysisApplication:6.1.2]
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[na:na]
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[na:na]
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[na:na]
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[na:na]
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482) ~[services.ImageAnalysisApplication:10.1.17]
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[na:na]
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[services.ImageAnalysisApplication:10.1.17]
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[na:na]
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340) ~[na:na]
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391) ~[na:na]
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[services.ImageAnalysisApplication:10.1.17]
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896) ~[na:na]
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744) ~[na:na]
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[services.ImageAnalysisApplication:10.1.17]
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[na:na]
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[na:na]
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[na:na]
		... 4 common frames omitted
Caused by: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Invalid instance. Missing required messages field. 
```

**To Reproduce**
Full codebase is available in the sample [**Use-case -Image analysis and Text Augmentation using Vision API, Langchain and Vertex AI**](https://github.com/GoogleCloudPlatform/serverless-production-readiness-java-gcp/tree/main/genai)

Snippet:
```
        if (prompt.length() > 0) {
          VertexAiChatModel vertexAiChatModel = VertexAiChatModel.builder()
                      .endpoint("...-aiplatform.googleapis.com:443")
                      .project(projectID)
                      .location(zone)
                      .publisher("google")
                      .modelName("chat-bison@001")
                      .temperature(0.1)
                      .maxOutputTokens(50)
                      .topK(0)
                      .topP(0.0)
                      .maxRetries(3)
                      .build();
          **modelResponse = vertexAiChatModel.generate(UserMessage.from(prompt));**
          logger.info("Result Chat Model: " + modelResponse.content().text());
        }
```

**Expected behavior**
The expected behaviour is a similar response as seen in the JIT image, where. modelResponse is assigned the response of the call. with no exception(s) encountered.

**Please complete the following information:**
- LangChain4j version: latest at. 0.25.0
- Java version:  21
- Spring Boot version (if applicable): latest at 3.2.1
- Google client library BOM: latest at 26.29.0

**Additional context**

### PR DESCRIPTION
**Pull request by ghost**
This PR is a fix for #444
- Missing metadata for Gson serialization was added for `langchain4j-vertex-ai` module
- `commons-logging` was excluded from dependencies as it causes troubles during native build

### CODE REVIEW

**Comment by langchain4j** [comment]
@geoand could you please take a look if you have a bit of time? Thank you!

**Review by geoand — APPROVED** [review]
The changes make sense to me!

**Comment by langchain4j** [comment]
@geoand awesome, thank you! Will add the same for other modules as well

**Comment by geoand** [comment]
💪

**Pull request merged**
