### PR TITLE
Update to Elasticsearch client 8.15.2

### PR DESCRIPTION
**Pull request by dadoonet**
## Issue

Relates to #1885

## Change

The Java client changed few APIs:

* script query is now easier to use without the need of `InlineScript`
* Range queries needs now to specifiy if you are using a `Double`, a `String` or a `Date`

## General checklist

- [X] There are no breaking changes
- [ ] I have added unit and integration tests for my change
- [ ] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [ ] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green
- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for changing existing embedding store integration

- [ ] I have manually verified that the `ElasticsearchEmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

### CODE REVIEW

**Comment by langchain4j** [comment]
@dadoonet thank you!

Tests are green. Should I merge?

**Comment by leduckhc** [comment]
When testing this PR with query/search functionality it throws error:

```
dev.langchain4j.store.embedding.elasticsearch.ElasticsearchRequestFailedException: co.elastic.clients.elasticsearch._types.ElasticsearchException: [es/search] failed: [illegal_argument_exception] [knn] queries cannot be provided directly, use the [knn] body parameter instead

Caused by: co.elastic.clients.elasticsearch._types.ElasticsearchException: [es/search] failed: [illegal_argument_exception] [knn] queries cannot be provided directly, use the [knn] body parameter instead
	at co.elastic.clients.transport.ElasticsearchTransportBase.getApiResponse(ElasticsearchTransportBase.java:345)
	at co.elastic.clients.transport.ElasticsearchTransportBase.performRequest(ElasticsearchTransportBase.java:147)
	at co.elastic.clients.elasticsearch.ElasticsearchClient.search(ElasticsearchClient.java:1965)
	at co.elastic.clients.elasticsearch.ElasticsearchClient.search(ElasticsearchClient.java:1984)
	at dev.langchain4j.store.embedding.elasticsearch.ElasticsearchConfigurationKnn.internalSearch(ElasticsearchConfigurationKnn.java:72)
	at dev.langchain4j.store.embedding.elasticsearch.ElasticsearchEmbeddingStore.search(ElasticsearchEmbeddingStore.java:297)
```

Code to reproduce:

```java

        EmbeddingStore<TextSegment> embeddingStore = ElasticsearchEmbeddingStore
                .builder()
                .configuration(ElasticsearchConfigurationKnn.builder().numCandidates(1000).build())
                .serverUrl(address)
                .userName(userName)
                .password(password)
                .indexName("games")
                .build();
        String text = "I like dungeons and dragons";
        Embedding vector = model.embed(text).content();
        // String id = embeddingStore.add(vector, TextSegment.from(text));

        EmbeddingSearchRequest request = EmbeddingSearchRequest.builder()
                .queryEmbedding(vector)
                .maxResults(5)
                .build();
        EmbeddingSearchResult<TextSegment> result = embeddingStore.search(request);
```

**Comment by dadoonet** [comment]
@langchain4j I'd like to see if I can optimize a bit the code before. That's why I made it a draft.
But feel free to merge as is if you want to release a version soonish.

**Comment by dadoonet** [comment]
@leduckhc what is the cluster version?

**Comment by langchain4j** [comment]
@dadoonet I plan to do a release at the end of the month, so no rush, please take your time

**Comment by leduckhc** [comment]
@dadoonet I double check and turns out I was testing this PR with older version of ES (docker). So for version of 8.15.2 of ES it seems  there's no exceptions for search/query.

Now, it is LGTM

**Comment by dadoonet** [comment]
@langchain4j It's now ready and the code is much better!

**Review by ghost — APPROVED** [review]
@dadoonet thank you!

**Pull request merged**
