### PR TITLE
[FEATURE]: Elasticsearch: add ann search options

### PR DESCRIPTION
**Pull request by CharleyXu**
[es k-nearest neighbor (kNN) search](https://www.elastic.co/guide/en/elasticsearch/reference/current/knn-search.html#approximate-knn-using-byte-vectors)
Add implementation of ann(Approximate kNN) in ElasticsearchEmbeddingStore

Elasticsearch supports two methods for kNN search:

[Approximate kNN](https://www.elastic.co/guide/en/elasticsearch/reference/current/knn-search.html#approximate-knn) using the knn search option or knn query
[Exact, brute-force kNN](https://www.elastic.co/guide/en/elasticsearch/reference/current/knn-search.html#exact-knn) using a script_score query with a vector function
In most cases, you’ll want to use approximate kNN. Approximate kNN offers lower latency at the cost of slower indexing and imperfect accuracy.

Added ann option when building ElasticsearchEmbeddingStore.

## Summary by CodeRabbit

- **New Features**
	- Enhanced search capabilities with the introduction of approximate and exact k-Nearest Neighbors (kNN) search functionalities.
	- Implemented cosine similarity for vector comparisons in searches.

### CODE REVIEW

**Comment by CharleyXu** [comment]
The solution is issue #759

**Comment by langchain4j** [comment]
Hi, thanks a lot! I it related to https://github.com/langchain4j/langchain4j/pull/712 ?

**Comment by CharleyXu** [comment]
> Hi, thanks a lot! I it related to #712 ?

Yes, the problem to be solved by PR #712 is the same. In comparison, the amount of code changes in my PR is very small, it still supports the original knn implementation, and is friendly to some lower versions of ES (7.x).

**Comment by CharleyXu** [comment]
I didn't realize at the time that #712 had solved the problem.

**Comment by langchain4j** [comment]
Closing in favor of https://github.com/langchain4j/langchain4j/pull/712

**Pull request closed without merging**
