### PR TITLE
Add OllamaChatModel and support it in spring-boot-starter

### PR DESCRIPTION
**Pull request by homich1991**
This commit adds OllamaChatModel and adds its support to spring-boot-starter module

### CODE REVIEW

**Comment by langchain4j** [comment]
hi @homich1991 thank you! please check https://github.com/langchain4j/langchain4j/pull/323

**Comment by homich1991** [comment]
Hi @langchain4j yes I saw this PR, but it doesn't add support for spring-boot-starter

**Comment by langchain4j** [comment]
Hi @homich1991 I am reworking spring boot starters now, can incorporate your changes from this PR if you are ok with it. Or I can ping you once I am done with other starters. What do you prefer?

**Comment by homich1991** [comment]
Hello,

Anything which would work best for you

Best Regards,

Roman Meerson

**Comment by langchain4j** [comment]
Closing this in favour of https://github.com/langchain4j/langchain4j-spring/pull/3

**Pull request closed without merging**
