### PR TITLE
Require max-attempts to be at least 1

### PR DESCRIPTION
**Pull request by jmartisk**
See https://github.com/quarkiverse/quarkus-langchain4j/issues/482 for the related discussion

### CODE REVIEW

**Comment by langchain4j** [comment]
Hi @jmartisk thanks a lot!
There is https://github.com/langchain4j/langchain4j/pull/981 already

**Comment by jmartisk** [comment]
Ok I've commented on that one too, it is slightly different, I'll let you decide what's better, and then just close the other one :)

**Comment by geoand** [comment]
As #981 was merged, should this be closed?

**Comment by jmartisk** [comment]
yeah

**Pull request closed without merging**
