### PR TITLE
Remove quarkus module

### PR DESCRIPTION
**Pull request by geoand**
This module is confusing people as its intent is not reflected by its name.
Moreover, this module is simply a copy of the previous version of the Azure OpenAI stuff that I will just copy in quarkus-langchain4j-azure-openai

### CODE REVIEW

**Comment by langchain4j** [comment]
@geoand I was keeping it and was planning to get rid of it once you are ready to copy. Please note that I just finished some changes related to token calculations, `AzureOpenAiStreamingChatModel` is affected, so it will be great if you can copy a fresh version once I push it (hopefully in 15 mins)

**Comment by geoand** [comment]
@langchain4j sure thing, not a problem at all

**Comment by langchain4j** [comment]
@geoand pushed, please check

**Comment by geoand** [comment]
Thanks I'll have a look tomorrow!

**Review by ghost — APPROVED** [review]
@geoand thank you!

**Comment by geoand** [comment]
🙏

**Pull request merged**
