### PR TITLE
Fixed null pointer exception

### PR DESCRIPTION
**Pull request by a-gull**
## Change
Fixed null pointer exception

### CODE REVIEW

**Comment by langchain4j** [comment]
HI @a-gull thank you!

What is the point to use `CompressingQueryTransformer` without `ChatMemory` though?

**Comment by a-gull** [comment]
> HI @a-gull thank you!
> 
> What is the point to use `CompressingQueryTransformer` without `ChatMemory` though?

Every time I have a rag conversation for the first time, ChatMemory is null, with the following error:

java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because "chatMemory" is null
	at dev.langchain4j.rag.query.transformer.CompressingQueryTransformer.transform(CompressingQueryTransformer.java:75)
	at dev.langchain4j.rag.DefaultRetrievalAugmentor.augment(DefaultRetrievalAugmentor.java:158)
	at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:136)
	at jdk.proxy2/jdk.proxy2.$Proxy179.chat(Unknown Source)
	at com.azor.service.ai_module.impl.AIChatServiceImpl.chat(AIChatServiceImpl.java:129)
       ...

**Comment by langchain4j** [comment]
@a-gull oh, I see.

Could you please provide the code how you configure memory and AI Service?

**Comment by a-gull** [comment]
> @a-gull oh, I see.
> 
> Could you please provide the code how you configure memory and AI Service?

Of course.
```
@Component
public class PersistentChatMemoryStore implements ChatMemoryStore {

    @Autowired
    private UserSessionService userSessionService;

    @Override
    public List<ChatMessage> getMessages(Object memoryId) {
        UserSession userSession = userSessionService.getById((Long) memoryId);
        return messagesFromJson(userSession.getMemory());
    }

    @Override
    public void updateMessages(Object memoryId, List<ChatMessage> messages) {
        String json = messagesToJson(messages);
        userSessionService.updateMemory((Long) memoryId, json);
    }

    @Override
    public void deleteMessages(Object memoryId) {
        userSessionService.clearSession((Long) memoryId);
    }
}
```
Part of the userSessionService code is as follows:
```
@Override
    public UserSession getById(long sessionId) {
        UserSession userSession = commonDao.load(UserSession.class, sessionId);
        if (userSession == null) {
            throw new BusinessException("The userSession does not exist");
        }
        return userSession;
    }

@Override
    public void updateMemory(long sessionId, String memory) {
        UserSession userSession = commonDao.load(UserSession.class, sessionId);
        if (userSession == null) {
            throw new BusinessException("The userSession does not exist");
        }
        userSession.setMemory(memory);
        commonDao.store(userSession);
    }

@Override
    public void clearSession(long sessionId) {
        UserSession userSession = commonDao.load(UserSession.class, sessionId);
        if (userSession == null) {
            throw new BusinessException("The userSession does not exist");
        }
        userSession.setMemory("[]");
        userSession.setHistory(new ArrayList<>());
        commonDao.store(userSession);
    }
```

**Comment by langchain4j** [comment]
> Every time I have a rag conversation for the first time, ChatMemory is null, with the following error:

Could you please elaborate? So after the second time all works fine? When and how is `ChatMemory` created?

**Comment by a-gull** [comment]
> > Every time I have a rag conversation for the first time, ChatMemory is null, with the following error:
> 
> Could you please elaborate? So after the second time all works fine? When and how is `ChatMemory` created?

It looks like I made a mistake, and now it's working fine.I'm sorry.

**Pull request closed without merging**
