### PR TITLE
add function call support to dashscope

### PR DESCRIPTION
**Pull request by luguoj**
## Context

The current dashscope SDK and langchain4j dashscope modules do not support function call functionality

## Change
Upgrade the dashscope sdk Java dependency version to 2.11.0.
Rewrote Generation, MultiModalConversation, and related classes, and extended the handler for function call related messages.
Implemented a method that supports function calls for the QwenChatModel class

### CODE REVIEW

**Comment by 648669556** [comment]
### 文档更新
After checking the related document ([dash scope doc](https://help.aliyun.com/zh/dashscope/developer-reference/api-details?spm=a2c4g.11186623.0.0.38365018Kl4iPA#86ef4d304bwsb)), it was found that:

Calling Function Upgrade Required: It is necessary to upgrade to version 2.12.0 or above for function calling. Please pay attention to whether further adjustments are needed here.
image

**Comment by langchain4j** [comment]
Issue: https://github.com/langchain4j/langchain4j/issues/934

**Comment by jiangsier-xyz** [comment]
@luguoj I hope not to rewrite the dashscope-sdk-java implementation which will make us stop upgrading it one day

**Comment by langchain4j** [comment]
Hi, thanks a lot!
Is it safe to merge and release?
Unfortunately I don't have api keys to test it.

**Comment by jiangsier-xyz** [comment]
> Hi, thanks a lot! Is it safe to merge and release? Unfortunately I don't have api keys to test it.

This patch has reimplemented some of the classes within the DashScope SDK. After the official version is upgraded, this should no longer be necessary. I'll review the official documentation again soon and may submit a new PR.

If you are about to release a version soon, then I suggest postponing this feature for the next one.

**Comment by langchain4j** [comment]
@jiangsier-xyz cool, thanks for info! Then it won't go into the release tomorrow.

**Comment by langchain4j** [comment]
Hi @jiangsier-xyz, what is the status of this PR? Is it still necessary?

**Pull request closed without merging**
