### PR TITLE
Throw error if more than one retriever/contentRetriever/retrievalAugm…

### PR DESCRIPTION
**Pull request by jmartisk**
…entor are set

As we discussed in https://github.com/quarkiverse/quarkus-langchain4j/pull/353#discussion_r1516119442

## Summary by CodeRabbit

- **New Features**
	- Enhanced AI services with new validation rules to ensure exclusive setting of components, improving system stability and predictability.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
@jmartisk what do you think about just checking if `context.retrievalAugmentor` is not present yet (!= null) instead of adding 3 new properties?

**Comment by jmartisk** [comment]
> @jmartisk what do you think about just checking if `context.retrievalAugmentor` is not present yet (!= null) instead of adding 3 new properties?

My concern was that in that case, it is possible that somebody just called `retrievalAugmentor()` multiple times, overriding the previous setting, so the error message wouldn't be able to say "just set one of these three things", which was my main point - to instruct the user that these three things are mutually exclusive. 

It would be confusing IMO if somebody:
- set a retriever
- set a content retriever
- and then received a message that RetrievalAugmentor is already set

**Comment by langchain4j** [comment]
@jmartisk I did not sleep well and my brain is melting now, so I might be hallucinating or misunderstanding 😅 But I guess you could still keep custom error messages, just change conditions in `if()` statements to `if(context.retrievalAugmentor() != null) `and get rid of 3 boolean properties and you will have absolutely the same behavior?

**Comment by jmartisk** [comment]
Sorry, it's a bit tough to explain :D

The point is that without these three booleans, it's not possible to tell whether the problem is that
1: somebody called one of the three methods multiple times (which is probably ok), or  that
2: somebody called two different methods (which is an error)

And even if we consider 1) as an error, then the error message doesn't know whether the problem was 1 or 2.
So somebody might get into scenario 2, but then they would have to receive an error message describing problem 1

**Comment by langchain4j** [comment]
@jmartisk ok, thanks for eli5, now I get it 😆 
I guess calling same method multiple times (potentially with different arguments) can be considered an error as well, but it is also ok as it is now

**Comment by jmartisk** [comment]
Yeah, and the point is to be able to throw an error message saying that "you tried to set two of them".
So that, for example in Quarkus, we won't have to add extra checks in the build-time processor to verify that only one of them is set.

**Review by ghost — COMMENTED** [review]
@jmartisk do you mind adding a few test cases?

**Comment by jmartisk** [comment]
> @jmartisk do you mind adding a few test cases?

Sure. Just a test that tries to set two of them and expects an error, or do you have something else in mind?

**Comment by langchain4j** [comment]
Ideally all combinations, as 3 booleans introduce 8 possibilities (I guess), very fertile ground for bugs :D

**Comment by jmartisk** [comment]
@langchain4j I've added a test :)

**Review by ghost — APPROVED** [review]
@jmartisk thanks a lot!

**Comment by langchain4j** [comment]
@jmartisk there is a bug :(
`AiServicesWithRagIT.should_use_legacy_retriever` fails, could you please check?

**Comment by jmartisk** [comment]
@langchain4j still have that problem somewhere? Got a stack trace? Doesn't look related to my PR, the test only verifies that you can't set more retrievers, but the test only uses one

**Comment by langchain4j** [comment]
@langchain4j yes, here is the stack trace:

```
dev.langchain4j.exception.IllegalConfigurationException: Only one out of [retriever, contentRetriever, retrievalAugmentor] can be set

	at dev.langchain4j.exception.IllegalConfigurationException.illegalConfiguration(IllegalConfigurationException.java:12)
	at dev.langchain4j.service.AiServices.contentRetriever(AiServices.java:343)
	at dev.langchain4j.service.AiServices.retriever(AiServices.java:323)
	at dev.langchain4j.service.AiServicesWithRagIT.should_use_legacy_retriever(AiServicesWithRagIT.java:555)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

**Comment by jmartisk** [comment]
@langchain4j Ah, yeah I see the error now. Will send PR in a few minutes! Sorry!

**Pull request merged**
