### PR TITLE
Issue 972: [FEATURE] Add name to dev.langchain4j.rag.content.retriever.EmbeddingStoreContentRetriever to improve logs

### PR DESCRIPTION
**Pull request by alwa**
Add name to dev.langchain4j.rag.content.retriever.EmbeddingStoreContentRetriever to improve logs

## Context
See: https://github.com/langchain4j/langchain4j/issues/972

## Change
Added display name option and a toString() implementation

## Checklist
Before submitting this PR, please check the following points:
- [x] I have added unit and integration tests for my change

### CODE REVIEW

**Comment by sjivan** [comment]
Any ETA to get this approved and merged? This is a useful feature

**Comment by sjivan** [comment]
@langchain4j @alwa This is very useful during multi-rag or conditional-rag flows for debugging purposes. Can we work on getting this approved?

**Comment by langchain4j** [comment]
@sjivan will try to review this week

**Review by ghost — APPROVED** [review]
@alwa thank you!

**Pull request merged**
