### PR TITLE
Feat(#1383): mutualise EmbeddingMatches handling

### LINKED ISSUE #1383: [AzureAiSearch] keep metadata for all kind of search
The default structure of an azure ai search index is a content ( and content_vector) and metadata with attributes as a map.

When we do a vector search, metadata are retrieved in the Content (via TextSegment). But for others types of search these metadata are lost.

Can we mutualise this code for all the search type ? : 
https://github.com/langchain4j/langchain4j/blob/30bf0aac087d803d9391c7018ba557b735f2b537/langchain4j-azure-ai-search/src/main/java/dev/langchain4j/store/embedding/azure/search/AbstractAzureAiSearchEmbeddingStore.java#L271-L300

### PR DESCRIPTION
**Pull request by fb33**
Closes #1383

### CODE REVIEW

**Comment by agoncal** [comment]
LGTM

**Review by ghost — DISMISSED** [review]

**Comment by langchain4j** [comment]
@fb33 there is a conflict now, could you please check?

**Comment by fb33** [comment]
> @fb33 there is a conflict now, could you please check?

I rebase onto main and I made modifications blindly because not all dependencies are available in oss sonatype repositories.

**Review by ghost — APPROVED** [review]
@fb33 thank you!

**Pull request merged**
