### PR TITLE
Create a Code of Conduct

### PR DESCRIPTION
**Pull request by jdubois**
This is the standard "Contributor Covenant Code of Conduct". It's a good practice to have a Code of Conduct, and it's even required by some companies in order to have their employees contributing to the project.

### CODE REVIEW

**Comment by maxandersen** [comment]
just really curious - which companies *require* a Code of conduct to have contributions ? I've heard and seen recommended - not required.

p.s. no objection/comment on adding one just curious about the required statement.

**Comment by edeandrea** [comment]
I've worked for large financial services and insurance companies that required it by their legal departments. I'd rather not name them directly.

**Comment by gsmet** [comment]
I think we need a broader discussion to make sure we want to apply this one to all the Quarkus/Quarkiverse projects. We need consistency.

**Comment by maxandersen** [comment]
@gsmet this isn't quarkus nor quarkiverse.

**Comment by gsmet** [comment]
Ah sorry too many notifications. Thought it was for quarkus-langchain4j.

**Review by ghost — APPROVED** [review]
@jdubois thank you!

**Pull request merged**
