### PR TITLE
Implement remove methods for InMemoryEmbeddingStore

### PR DESCRIPTION
**Pull request by InAnYan**
## Issue
[https://github.com/langchain4j/langchain4j/issues/301](https://github.com/langchain4j/langchain4j/issues/301)

## Change
I've implemented remove methods for InMemoryEmbeddingStore.

Current problems:
1. I'm not completely sure how to test all of this. And, as I've seen, you don't fully test it too)
2. There is a very nasty problem with `removeAll(Filter filter)` . Let me try to break it in small pieces:
   1. `EmbeddingStore`'s are parametrized with `Embedded` type parameter.
   2. `removeAll(Filter filter)` method in `EmbeddingStore` accepts `Filter`.
   3. `Filter` accepts `Metadata` object.
   4. `Metadata` object is stored in `TextSegment`.
   5. `TextSegment` is usually what is `Embedded`. But it's not guaranteed.

How my pull request deals with this problem: 
1) for every entry in `InMemoryEmbeddingStore` check the type of `Embedded`. 
2) If it's a `TextSegment`, then proceed.
3) If it's not, then raise `UnsupportedOperationException`.
The issue with this strategy is that we perform the check for every entry. I haven't found a way in Java to check the type of type parameter (because it's erasured in runtime). (*In C++, for example, there are `constexpr if`, `<type_traits>`, `std::is_same<U, V>`, explicit specialization, etc.*)

We could solve this problem if `InMemoryEmbeddingStore` would support only `TextSegment` as `Embedded`, but that's a breaking change.

I could also not implement this method, but, I really really need it in my project (if we chose to stick with `InMemoryEmbeddingStore`).
  

## General checklist

- [x] There are no breaking changes
- [ ] I have added unit and integration tests for my change
- [ ] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [ ] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)

## Checklist for changing existing embedding store integration

- [ ] I have manually verified that the `{NameOfIntegration}EmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

### CODE REVIEW

**Comment by langchain4j** [comment]
Hi @InAnYan thanks a lot!

> I'm not completely sure how to test all of this. And, as I've seen, you don't fully test it too)

I think we can extract tests from `PgVectorEmbeddingStoreRemoveIT` into `EmbeddingStoreWithRemovalIT` in a `langchain4j-core` module, similar to `EmbeddingStoreIT` and every `EmbeddingStore` that implements removal will extend this test. WDYT?

Regarding the `TextSegment` vs `Embedded`, I plan to review this "problem" soon and see if this sohuld be changed. Originally there was an idea to allow other types of objects to be stored in the `EmbeddingStore`, and I think we might soon start supporting this.
Your current implementation seems ok.

**Comment by InAnYan** [comment]
Hi, @langchain4j. Been working on implementing tests.

Changes I made:
1. I've created `EmbeddingStoreWithRemovalIT` as you proposed. Now I see where the actual tests are)
2. Implemented `InMemoryEmbeddingStoreWithRemovalIT`.
3. Also changed methods a little bit to conform to internal standards of your library.

So far I have these questions:
1. PGVector somehow handles `null` embedded values. However my code relies that `embedded` is present. It throws "not supported operation". Here are two ways of how to solve this issue:
	1) What I did is I added `TextSegment`s to testing code. I did this because I'm not really sure how `EmbeddingStore`s implemenation should handle `null` embedded values.
	2) Another option is to change `InMemoryEmbeddingStore.removeAll(Filter filter)`, change the lambda, and ignore `null` embedded. That way I completely don't change any testing code from `PgVectorStoreRemoveIT`.
2. `PgVectorStoreRemoveIT` relies on `EmbeddingStore.findRelevant` method which is considered depricated. Should we somehow change the test cases in `EmbeddingStoreWithRemovalIT` to accomodate this?
3. Should I delete `PgVectorStoreRemoveIT`? Or, actually, make it use the class I made: `EmbeddingStoreWithRemovalIT`.

**Comment by langchain4j** [comment]
Hi @InAnYan 

> PGVector somehow handles null embedded values. However my code relies that embedded is present. It throws "not supported operation". Here are two ways of how to solve this issue:
> What I did is I added TextSegments to testing code. I did this because I'm not really sure how EmbeddingStores implemenation should handle null embedded values.
> Another option is to change InMemoryEmbeddingStore.removeAll(Filter filter), change the lambda, and ignore null embedded. That way I completely don't change any testing code from PgVectorStoreRemoveIT.

I am not sure I completely understand the problem, could you please elaborate? Usually `EmbeddingStore` can store `Embedding` alone, without `TextSegment`. This is one of the use cases when text data is stored elsewhere and correlated by ID.

> PgVectorStoreRemoveIT relies on EmbeddingStore.findRelevant method which is considered depricated. Should we somehow change the test cases in EmbeddingStoreWithRemovalIT to accomodate this?

Would be great to use the new `EmbeddingStore.search()` API!

> Should I delete PgVectorStoreRemoveIT? Or, actually, make it use the class I made: EmbeddingStoreWithRemovalIT.

Yes, please make `PgVectorStoreRemoveIT` inherit tests from `EmbeddingStoreWithRemovalIT`

**Comment by InAnYan** [comment]
Hello, @langchain4j. Here is my work:
1. About `null` embedded value. Never mind, now I see that it is allowed to use it, so I just skip it in `removeAll(Filter filter)`, because it doesn't contain any metadata.
2. I've changed the usages of `EmbeddingStore.findRelevant`, now they use `search`.
3. `PgVectorEmbeddingStoreRemoveIT` now extends from `EmbeddingStoreWithRemovalIT`.

Tests for `InMemoryEmbeddingStore` and `PgVectorEmbeddingStore` all work.

---

Besides, why mark `EmbeddingStore.findRelevant` as deprecated? Why not implement it like this:
```java
List<EmbeddingMatch<TextSegment>> findRelevant(Embedding embedding, int maxResults) {
	EmbeddingSearchRequest embeddingSearchRequest = EmbeddingSearchRequest
            .builder()
            .queryEmbedding(embedding)
            .maxResults(maxResults)
            .build();

    return search(embeddingSearchRequest).matches();
}

**Comment by langchain4j** [comment]
> Besides, why mark EmbeddingStore.findRelevant as deprecated?

The old `findRelevant` API is too inflexible to be extended with more features. Going forward, only the new `search` API will be extended with more features.

**Review by ghost — APPROVED** [review]
@InAnYan thank you!

**Pull request merged**
