### PR TITLE
Adding Azure CLI script to deploy the Azure AI Search resources

### PR DESCRIPTION
**Pull request by agoncal**
Adding Azure CLI script to deploy the Azure AI Search resources needed to pass the IT tests `AzureAiSearchEmbeddingStoreIT` and `AzureAiSearchContentRetrieverIT`

cc @jdubois I've used part of your existing script #Thanks

### CODE REVIEW

**Review by ghost — APPROVED** [review]
@agoncal thanks! BTW, how do you usially run these scripts? I am using Windows...

**Comment by Martin7-1** [comment]
> @agoncal thanks! BTW, how do you usially run these scripts? I am using Windows...

@langchain4j I am using [WSL](https://learn.microsoft.com/en-us/windows/wsl/install) on Windows. It's a good choice rather than virtual machine.

**Comment by langchain4j** [comment]
@Martin7-1 thanks, I've used WSL a few days a go to run a similar script (for Azure OpenAI), but had many issues... Need to check what is exactly wrong

**Comment by agoncal** [comment]
I've added a comment to the shell scripts: https://github.com/langchain4j/langchain4j/pull/1403

**Pull request merged**
