### PR TITLE
Bugfix/fix 0 retry times

### PR DESCRIPTION
**Pull request by VaderKai**
## Context

#928 
## Change

Fix wireless retry when retry count is 0
Fix the total number of executions to 1+ retry times
if retry times is less than or equal to 0 is 0
## Checklist
Before submitting this PR, please check the following points:
- [x] I have added unit and integration tests for my change
- [x] All unit and integration tests in the module I have added/changed are green
- [x] All unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules are green
- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added my new module in the [BOM](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-bom/pom.xml) (only when a new module is added)

## Checklist for adding new embedding store integration
- [ ] I have added a {NameOfIntegration}EmbeddingStoreIT that extends from either EmbeddingStoreIT or EmbeddingStoreWithFilteringIT

### CODE REVIEW

**Comment by jmartisk** [comment]
You're turning "attempts" into "retries" here I'd say. If it's called 'attempts', shouldn't 0 mean an error (`IllegalArgumentException`), and 1 to attempt exactly once?
That is, unless we rename the whole thing to "retries" in the code, but it's currently named "attempts".

**Comment by VaderKai** [comment]
> 

so we need do a choice,the utils name is RetryUtils,we can rename the method name or forbidan 0 attempts params,
i think rename is more reasonably,but changes is big,do you thinking about it?

**Comment by jmartisk** [comment]
I would personally keep it as attempts, so 0 means error, and 1 means try exactly once. But it depends what @langchain4j thinks

**Comment by VaderKai** [comment]
> I would personally keep it as attempts, so 0 means error, and 1 means try exactly once. But it depends what @langchain4j thinks

I've changed the number of attempts to a minimum of 1, and 1 for illegal parameters (<=0).

**Review by ghost — APPROVED** [review]
@VaderKai thank you!

**Pull request merged**
