### PR TITLE
Add getters to AnthropicCreateMessageRequest and change scope of attributes

### PR DESCRIPTION
**Pull request by edeandrea**
This should have been done in #834

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by langchain4j** [comment]
@edeandrea thanks!

**Comment by edeandrea** [comment]
Thank you @langchain4j ! Do you know when you are planning another release that would include this?

**Comment by edeandrea** [comment]
Hi @langchain4j I was just curious when you might be planning another release which includes this? I'm working on a downstream change (https://github.com/quarkiverse/quarkus-langchain4j/pull/438) and I'm blocked there until this is released.

**Comment by langchain4j** [comment]
Hi @edeandrea, sorry for the delay, I plan to do one on 15th April.

**Comment by edeandrea** [comment]
No worries at all I'm sure you're busy! Thank you for the update!

**Pull request merged**
