### PR TITLE
Add a variable to optionally update the index in AzureAISearchContentRetriver

### PR DESCRIPTION
**Pull request by jdubois**
See #795

### CODE REVIEW

**Comment by jdubois** [comment]
Ping @showpune for awareness

**Review by ghost — APPROVED** [review]
@jdubois thank you!

**Comment by langchain4j** [comment]
@jdubois all tests in `AzureAiSearchContentRetrieverIT` are failing for me (locally) wit hthe following exception:

```
java.lang.IllegalArgumentException: for full-text search, dimensions must be 0

	at dev.langchain4j.internal.Exceptions.illegalArgument(Exceptions.java:19)
	at dev.langchain4j.internal.ValidationUtils.ensureTrue(ValidationUtils.java:112)
	at dev.langchain4j.rag.content.retriever.azure.search.AzureAiSearchContentRetriever.<init>(AzureAiSearchContentRetriever.java:77)
	at dev.langchain4j.rag.content.retriever.azure.search.AzureAiSearchContentRetriever$AzureAiSearchContentRetrieverBuilder.build(AzureAiSearchContentRetriever.java:392)
	at dev.langchain4j.rag.content.retriever.azure.search.AzureAiSearchContentRetrieverIT.createContentRetriever(AzureAiSearchContentRetrieverIT.java:60)
	at dev.langchain4j.rag.content.retriever.azure.search.AzureAiSearchContentRetrieverIT.<init>(AzureAiSearchContentRetrieverIT.java:44)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)


```

**Comment by jdubois** [comment]
@langchain4j I'm checking right now

**Comment by jdubois** [comment]
`AzureAiSearchContentRetriever.java:77` is https://github.com/langchain4j/langchain4j/blob/7534884854d7c9c9dc3160a00c9972707013489e/langchain4j-azure-ai-search/src/main/java/dev/langchain4j/rag/content/retriever/azure/search/AzureAiSearchContentRetriever.java#L77 which is a comment, so locally you're not on the latest version I'm afraid

**Comment by langchain4j** [comment]
Damn, my bad, pardon!

**Pull request merged**
