### PR TITLE
add BOM to manage artifacts

### PR DESCRIPTION
**Pull request by Martin7-1**
see #217, it's a good way to manage artifacts.

Now users can use code below to import dependency:

```xml
    <dependencyManagement>
        <dependencies>
              <dependency>
                  <groupId>dev.langchain4j</groupId>
                  <artifactId>langchain4j-bom</artifactId>
                  <version>${langchain4j.version}</version>
                  <type>pom</type>
                  <scope>import</scope>
              </dependency>
        </dependencies>
    </dependencyManagement>
```

### CODE REVIEW

**Review by Heezer — APPROVED** [review]
Looks good from side! 👍

**Comment by langchain4j** [comment]
@Martin7-1 correct me if I am wrong, but I think this is not what was meant in https://github.com/langchain4j/langchain4j/issues/217. As far as I understood, the user wants a simple way to import all modules at once. The provided change helps with importing only versions of modules (not the modules themselves), but the versions are always the same, so there should be no problem with keeping them in sync even without BOM. Let me double check with the user...

**Comment by Martin7-1** [comment]
@langchain4j Actually there doesn't seem to be a scenario where all modules need to be imported. Our modules contains different model providers and different embedding stores, and users just need to choose one of them. I think in #217, the user wants a way to manage related `langchain4j` modules, when updated, the user doesn't need to fix the conflict between modules(e.g. embedding store implementations depend on `langchain4j-core` module, change `EmbeddingStore` interface may need to change more than one module version).

You can wait until you have double checked with the user before reviewing the PR.

**Comment by langchain4j** [comment]
@Martin7-1 I am not sure where from conflict between module versions can potentially come from. Every release we update the version for every dependency. So langchain4j-core:0.23.0 is compatible with langchain4j-vespa:0:23:0 and so on. This means that ideally users should update the version only in one place (if they use variables like ${langchain4j.version}), or for every imported module (but in any case to the same version).

**Comment by Martin7-1** [comment]
@langchain4j I'm going to close this PR because the user didn't response, will reopen it if the user clarify his/her use case

**Pull request merged**
