### PR TITLE
[Draft] ChatLanguageModel: allow setting parameters dynamically

### PR DESCRIPTION
**Pull request by ghost**
## Issue
https://github.com/langchain4j/langchain4j/issues/837

## Change
Drafted flexible `(Streaming)ChatLanguageModel` API that allows specifying common model parameters (e.g. model name, temparature, etc) for each request.
Comparison table: https://docs.google.com/spreadsheets/d/1hOsbbAz9-qXCrnq_TXW-Q_AIAlssPLz9/edit?gid=1554605342#gid=1554605342

## General checklist
- [ ] There are no breaking changes
- [ ] I have added unit and integration tests for my change
- [ ] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [ ] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green
- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)

### CODE REVIEW

**Comment by fmatar** [comment]
Would this also support passing of apiKeys / baseUrl / organizationId?

**Comment by langchain4j** [comment]
@fmatar I will check if/how that can be supported

**Comment by fmatar** [comment]
@langchain4j one of the approaches I implemented was to use the raw rest client for that purpose. 

Then I pass all my chatCompletion request along with the security keys to the request and execute. 

One major blocking factor was the passing of the model objects by ai4j since they're not serializable and I ended up writing the required serialized for them. 

Happy to assist in anyway since this is a major roadblock we'd like to resolve

**Comment by cv-msan** [comment]
> @fmatar我将检查如何支持那件事

We now have tables in MySQL specifically designed to maintain various model parameters, and we want users to be able to dynamically switch between different models at any time. When is this dynamic switching feature expected to be supported?

**Comment by langchain4j** [comment]
@cv-msan which parameters should be dynamic to support your use case? Hopefully this will be included in the next release, in the mid of december

**Comment by cv-msan** [comment]
> @cv-msan哪些参数应该动态以支持您的用例？希望这将在下一个月中旬的下一个版本中包含
 apiKey、baseUrl、modelName For now, there are three necessary ones

**Comment by cv-msan** [comment]
You can check if there are any other configurable parameters in other models for the rest

**Comment by cv-msan** [comment]
From a business perspective, there is a model configuration list where you can set the default model to use for Rag conversations and switch between multiple models. Currently, I have implemented it myself, but I feel that the writing is not very good. If your official team can implement dynamic model switching instead of creating an immutable model in the form of Spring beans, it would be quite cool
image

**Comment by langchain4j** [comment]
@cv-msan I guess it is feasible, `modelName` is already dynamic in this PR. Regarding `apiKey` and `baseUrl`: we need to think a bit more about it

**Comment by cv-msan** [comment]
Okay, I'm really looking forward to your updates

**Comment by langchain4j** [comment]
Superceded by https://github.com/langchain4j/langchain4j/pull/1989

**Pull request closed without merging**
