### PR TITLE
Run under JDK 23

### PR DESCRIPTION
**Pull request by kpavlov**
This allows to catch incompatibilities with latest released JDK earlier

## Change

Run under JDK 23 This allows to catch incompatibilities with latest released JDK earlier

Don't cancel unit tests on failure. [Doc](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow#handling-failures)

Always run unit tests

This pull request to the `.github/workflows/main.yaml` file includes changes to improve the build matrix and error handling for Java builds. The most important changes include adding a new Java version to the matrix, modifying the build strategy, and updating the conditions for running integration tests.

Improvements to build matrix and error handling:

* Added Java 23 to the build matrix and included an `experimental` flag for each Java version. (`.github/workflows/main.yaml`)
* Changed the `runs-on` specification to `ubuntu-latest` and added the `continue-on-error` property based on the `experimental` flag. (`.github/workflows/main.yaml`)
* Set `fail-fast` to `false` in the build strategy to allow all matrix jobs to run even if one fails. (`.github/workflows/main.yaml`)

Updates to build steps and conditions:

* Removed the `-Dgib.disable=false -Dgib.referenceBranch=__branch_before` options from the `Compile and test` step. (`.github/workflows/main.yaml`)
* Updated the condition for running integration tests to exclude experimental builds. (`.github/workflows/main.yaml`)

## General checklist

- [x] There are no breaking changes
- [ ] I have added unit and integration tests for my change
- [ ] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [ ] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for adding new maven module

- [ ] I have added my new module in the root `pom.xml` and `langchain4j-bom/pom.xml`

## Checklist for adding new embedding store integration

- [ ] I have added a `{NameOfIntegration}EmbeddingStoreIT` that extends from either `EmbeddingStoreIT` or `EmbeddingStoreWithFilteringIT`
- [ ] I have added a `{NameOfIntegration}EmbeddingStoreRemovalIT` that extends from `EmbeddingStoreWithRemovalIT`

## Checklist for changing existing embedding store integration

- [ ] I have manually verified that the `{NameOfIntegration}EmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

### CODE REVIEW

**Comment by kpavlov** [comment]
Caught a regression related to using Lombok under JDK23 😇  https://github.com/langchain4j/langchain4j/actions/runs/11495320279/job/31994597511

**Comment by langchain4j** [comment]
@kpavlov it still fails

**Comment by kpavlov** [comment]
@langchain4j, Fixing building under jdk 23 is out of scope of this PR. Aa this job is experimental, it is allowed to fail and does not fail the whole build. Compilation issue and getting rid of lombok  I will address in a separate PR.

Will have a closer look at the current problem. Maybe bad merge

**Comment by kpavlov** [comment]
Let #1979 go first

**Comment by kpavlov** [comment]
#1987 should probably fix JDK 23 build

**Comment by kpavlov** [comment]
Now Mockito is too old for JDK23. 
```
Caused by: org.mockito.exceptions.base.MockitoInitializationException: 
Could not initialize inline Byte Buddy mock maker.
```
Let's merge enabling Java 23 and fix Mockito in a separate PR

**Review by ghost — APPROVED** [review]
@kpavlov thank you!

**Pull request merged**
