### PR TITLE
#1652 Run OpenRewrite to migrate code to java 17

### LINKED ISSUE #1652: Raise the baseline to Java 17

### PR DESCRIPTION
**Pull request by kpavlov**
## Issue

Closes #1652

## Change

Run OpenRewrite [recipe](https://docs.openrewrite.org/running-recipes/popular-recipe-guides/migrate-to-java-17) to migrate code to Java 17.

This pull request includes various changes to improve code readability and consistency, primarily by replacing `String.format` with the more modern `String.formatted` method and using pattern matching for `instanceof` checks. Additionally, it introduces multi-line string literals for better readability in some cases.

### Code Readability and Consistency Improvements:

* Replaced `String.format` with `String.formatted` in multiple files to modernize string formatting:
  * `AmazonS3Source.java`
  * `AzureBlobStorageSource.java`
  * `TencentCosSource.java`
  * `LanguageModelSqlFilterBuilder.java`
  * `HtmlToTextDocumentTransformer.java`

* Used pattern matching for `instanceof` to simplify type checks and casting:
  * `HtmlToTextDocumentTransformer.java`
  * `SqlFilterParser.java`

### Multi-line String Literals:

* Introduced multi-line string literals for better readability:
  * `LanguageModelSqlFilterBuilder.java`
  * `HtmlToTextDocumentTransformerTest.java` [[1]](diffhunk://#diff-7a0a64d65a39002b9c27ae5a141edfc1ed5370d6e817db08d2219ea0dc6b4b86L38-R49) [[2]](diffhunk://#diff-7a0a64d65a39002b9c27ae5a141edfc1ed5370d6e817db08d2219ea0dc6b4b86L90-R102) [[3]](diffhunk://#diff-7a0a64d65a39002b9c27ae5a141edfc1ed5370d6e817db08d2219ea0dc6b4b86L130-R143)

### Build and Configuration:

* Added multi-threading options to `Makefile` and `.mvn/maven.config` for improved build performance:
  * `.mvn/maven.config`

These changes enhance the maintainability and performance of the codebase by adopting modern Java practices and optimizing build configurations.

## General checklist

- [ ] There are no breaking changes
- [ ] I have added unit and integration tests for my change
- [ ] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [ ] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for adding new maven module

- [ ] I have added my new module in the root `pom.xml` and `langchain4j-bom/pom.xml`

## Checklist for adding new embedding store integration

- [ ] I have added a `{NameOfIntegration}EmbeddingStoreIT` that extends from either `EmbeddingStoreIT` or `EmbeddingStoreWithFilteringIT`
- [ ] I have added a `{NameOfIntegration}EmbeddingStoreRemovalIT` that extends from `EmbeddingStoreWithRemovalIT`

## Checklist for changing existing embedding store integration

- [ ] I have manually verified that the `{NameOfIntegration}EmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

### CODE REVIEW

**Comment by langchain4j** [comment]
@kpavlov thank you! Would it be possible to split this PR in smaller parts, so that I could realistically review it? I know that this is an automatic change, but I still want to review what I am approving.

**Comment by langchain4j** [comment]
I would suggest to have only one type of change in a single PR (e.g. `formatted`) and make sure it is no bigger than 50 files.

**Comment by kpavlov** [comment]
This is difficult to split it by change, bacause it's OpenRewrite appying many rules, but I will submit multiple PRs for different modules to make it reviewable.

**Comment by kpavlov** [comment]
Part 1: #1970

**Pull request closed without merging**
