### PR TITLE
New low-level API to specify tool parameters

### LINKED ISSUE #896: [FEATURE] Support for custom types in openai tool/function interface
**Is your feature request related to a problem? Please describe.**

Currently, only Java's built-in types (boolean, byte, short, int, long, float, double, BigDecimal, BigInteger, String, Array, and Array-like) are supported as parameters for tools or functions. Still, custom types may be needed for convenience.

*Example*: Suppose I am developing database tools; each tool works with a specific column type. Without custom types, I would need to repeatedly specify database, table, and column names in each tool's interface. 
```java
class DatabaseToolkit {
    @Tool
    void listByDatetime(
        @P("Database name, it can be ....")
        String dbName,
        @P("Table name, it can be ....")
        String tableName,
        @P("Column name, it can be ....")
        String columnName,
        long start, long end) {
        // ...
    }

    @Tool
    void listByMatch(
        // bad: repeated definition and description
        @P("Database name, it can be ....")
        String dbName,
        @P("Table name, it can be ....")
        String tableName,
        @P("Column name, it can be ....")
        String columnName,
        String pattern) {
        // ...
    }
   
    // more repeated... 
}
```

By organizing these names in a custom type like Column, I can avoid repeating them in every tool or function interface. 

```java
class Column {
        @P("Database name, it can be ....")
        String dbName;
        @P("Table name, it can be ....")
        String tableName;
        @P("Column name, it can be ....")
        String columnName;
        // ...
}

class DatabaseToolkit {
    @Tool
    void listByDatetime(
        Column column,
        long start, long end) {
        // ...
    }

    @Tool
    void listByMatch(
        Column column,
        String pattern) {
        // ...
    }
   
    // more repeated... 
}
```

Additionally, I can manipulate multiple columns at once by using a list of Column instances. Achieving this functionality would be challenging without custom types.

**Describe the solution you'd like**

The current implementation describes the tool or function interface, including all its parameters, in [JsonSchema](https://json-schema.org/understanding-json-schema/), as required by [OpenAI doc](https://platform.openai.com/docs/api-reference/chat/create#chat-create-tools). Python LangChain does so using [pydantic](https://github.com/pydantic/pydantic). By following this convention, we can support custom type to be tool/function parameters in two steps:
- Build a JsonSchema Generator to convert correctly annotated custom type into JsonSchema;
- Build a JsonSchema Validator to validate and coerce the argument generated by LanguageModel into the custom type.

To do so, one can extend [ToolSpecifications](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-core/src/main/java/dev/langchain4j/agent/tool/ToolSpecifications.java) by generating JsonSchema for custom types. To bind JsonSchema attributes to the custom type and its fields, new annotations can be introduced, or existing annotations like [Jackson-Annotations](https://github.com/FasterXML/jackson-annotations/wiki/Jackson-Annotations) can be adopted directly. In [DefaultToolExecutor](https://github.com/langchain4j/langchain4j/blob/main/langchain4j/src/main/java/dev/langchain4j/agent/tool/DefaultToolExecutor.java), one should add code to validate the arguments according to the JsonSchema or the corresponding annotations, and then coerce them to corresponding types, including custom ones.

Several points to consider:
-  Composition: When a custom type is derived, we should recursively compose the schemas of its superclasses using the `allOf` attribute in JsonSchema.
-  Polymorphism: If a custom type is abstract or a superclass that can accept instances of its subclasses, we should use the `oneOf` attribute in JsonSchema.

*Benefit*: This solution is lightweight and requires minimal changes to the current code. It also avoids adding additional dependencies to the langchain4j core library.

*Shortcoming*: It may reinvent the wheel.

*NOTE*: Supporting custom type parameters will break the token counting process of [OpenAiTokenier](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-open-ai/src/main/java/dev/langchain4j/model/openai/OpenAiTokenizer.java) as it assumes the parameters can only be Java built-in types when estimating tokens in tool specification. Once we support custom type, we should update OpenAiTokenizer's code logic.

**Describe alternatives you've considered**

The proposed solution might be reinventing the wheel since there are many open-source JsonSchema generators in Java. Here are several alternatives:
- The [victools/jsonschema-generator](https://github.com/victools/jsonschema-generator) tool supports generating and validating JsonSchema with respect to annotations from Jackson, Jakarta, javax, and Swagger.
- The [networknt/json-schema-validator](https://github.com/networknt/json-schema-validator) tool supports the [JSON Schema Core Draft v4, v6, v7, v2019-09 and v2020-12](http://json-schema.org/latest/json-schema-core.html) specification for JSON schema validation with respect to Jackson.

*Benefit*: One big benefit of adopting these existing approaches is that once validated, you can directly deserialize the JSON string back to beans since they respect serialization frameworks like Jackson.

*Shortcoming*: However, using existing JsonSchema generators may introduce more dependencies to the core library, and their features could be overly broad for the tool/function calling situation.

**Additional context**

My concerns include:
- Does langchain4j really need custom-type parameters?
- If so, is there a current process to support custom-type parameters?
- If not, what is the preferred approach: implementing a lightweight JsonSchema directly into langchain4j (similar to the initial solution) or using an existing JsonSchema Generator (like the other options)?

### LINKED ISSUE #1480: [BUG] A list of objects is not serialised correctly
In a recent release, tool parameters support POJOs. I am however having problem getting it to work when the POJO is wrapped in a collection.

**Describe the bug**
Here is what happens when a tool param is a collection of POJOS: The contents of data is valid, but the structure is wrong. Meaning, if the param is `java.util.List<MyPojo>`, the actual object is an ArrayList, containing LinkedTreeMap. The contents of the map is correct though(meaning keys match those of MyPojo).

**Log and Stack trace**
n/a

**To Reproduce**
```java
    public record AiVariant(String type, String value) {}

    @Tool
    public void saveVariants(
        List<AiVariant> variants
    ) { }

    @Bean
    public ChatLanguageModel openAiChatModel() {
        return OpenAiChatModel.builder()
            .apiKey(openAiApiKey)
            .responseFormat("json_object")
            .build();
    }

    //The RAG is probably not needed for this example. 
    @Bean
    public AiAssistant aiAssistant(ChatLanguageModel openAiChatModel, ContentRetriever rag, ContentTools contentTools) {
        return AiServices.builder(AiAssistant.class)
            .chatLanguageModel(openAiChatModel)
            .tools(contentTools)
            .chatMemory(MessageWindowChatMemory.withMaxMessages(10))
            .contentRetriever(rag)
            .build();
    }
...

public interface AiAssistant {
    @SystemMessage("Json")
    String chat(String message);
}

...

@Component
public class Test implements CommandLineRunner {
   
    @Autowired private AiAssistant aiAssistant;

    @Override
    public void run(final String... args) throws Exception {
        var chat = aiAssistant.chat("Save variants with type jurisdiction and value EU");

```

**Current vs Expected behavior**
_Current behavior_:
Screenshot 2024-07-17 at 17 08 42

_Expected behavior_: A list of objects of type "AiVariants", and not LinkedTreeMap.

**Please complete the following information:**
- LangChain4j version:
langchain4j, langchain4j-open-ail & langchain4j-easy-rag: 0.32.0
- LLM(s) used: 
Default version
- Java version:
JDK 21 
- Spring Boot version (if applicable): 
3.3.1

**Additional context**

### LINKED ISSUE #1858: [BUG] Tool function with parameter List<Integer> incorrectly parsed as List<Double>
I've defined a tool with a function like this.

```
        @Tool("Finds books based on filters. Returns a json array of books with different attributes. At least one parameter is required.")
        String findBooks(
            @P(value = "A filter to find/search books by their name.", required = false) String match,
            @P(value = "A JSON array of authors (or user) IDs to filter by authors.", required = false) List<Integer> authors,
        {
        }

```
The LLM made a call to the tool as below.

```
{
    "role" : "assistant",
    "tool_calls" : [ {
      "id" : "call_8yxDdgTdIN4Ljzo7jXIsoW3B",
      "type" : "function",
      "function" : {
        "name" : "findBooks",
        "arguments" : "{\"arg1\":[123]}"
      }
    } ]
  }

```

As you can see the LLM returned an array of Integer, but in the function I get the value 123.0. Looks like an issue with parsing.

### LINKED ISSUE #1865: [BUG] ToolSpecification of List<Enum> or []Enum parameter is incorrect
**Describe the bug**
I've tried specifying a tool parameter as `List<Enum> and Enum[]`. But the tool parameter sent to the LLM is incorrect.

e.g if the tool parameter is defined as

```
public enum ColorChoices {
     Red, Blue, Green, Yellow
};

 @P(value = "Specify all the color options chosen by the user.", required = true) List<ColorChoices> colors

OR

 @P(value = "Specify all the color options chosen by the user.", required = true) ColorChoices[] colors

```

**Log and Stack trace**
The log output shows this as part of the request.

```
         "arg7" : {
            "type" : "array",
            "description" : "Specify all the color options chosen by the user.",
            "items" : {
              "type" : "object",
              "properties" : { },
              "required" : [ ]
            }
          },
```
**Expected behavior**
In the OpenAI schema I can write this as..

```
"arg6": {
        "type": "array",
        "items": {
          "type": "string",
          "enum": [
            "Red",
            "Blue",
            "Green",
            "Yellow",
          ]
        },
        "description": "Specify all the color options that chosen by the user."
      }

```

If I don't define it as either an Array or List, then the translation looks correct.

```
   @P(value = "Specify all the color options that chosen by the user." required = true) ColorChoices colors)

"arg6" : {
            "type" : "string",
            "description" : "Specify all the color options chosen by the user.",
            "enum" : [ "Red", "Blue", "Green", "Yellow" ]
          },
```

**Please complete the following information:**
- LangChain4j version: 0.35
- LLM(s) used: gpt-4o-mini
- Java version: 11

### LINKED ISSUE #1881: [BUG] Tool calls skip description of properties and required for json objects when they are part of a list
Tool calls skip description of properties and required for json objects when they are part of a list.

For example consider the tool definition.

    class MyTool {

    @Tool("get today's temperature for a city")
    fun getTemperature(@P("city, both city name and airport code are required", required = true) city: City): Double {
        return 0.0
    }

    class City(@Description("name of the city") var name: String,
               @Description("airport code of the city") var airportCode: String)
    }
    }

`
{
  "function": {
    "name": "getTemperature",
    "description": "get today's temperature for a city",
    "parameters": {
      "type": "object",
      "properties": {
        "city": {
          "description": "city, both city name and airport code are required",
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "description": "name of the city"
            },
            "airportCode": {
              "type": "string",
              "description": "airport code of the city"
            }
          },
          // This is missing  "required": ["name", "airportCode"] // This is missing 
        }
      },
      "required": [
        "city"
      ]
    }
  },
  "type": "function"
}
`

**Expected behavior**
The required for the property "name" and "airportCode" are missing.

**Please complete the following information:**
- LangChain4j version: 0.35.0
- LLM(s) used: OpenAI
- Java version: 17
- Spring Boot version (if applicable): 3.3.0

**Additional context**
The same can be manually constructed programmatically using ToolSpecification builder, but does not work when tools are defined in code.

### PR DESCRIPTION
**Pull request by ghost**
## Issue
Closes #896
Fixes #1480
Fixes #1881
Fixes #1858
Fixes #1865

## Context
Schema for tool parameters in the low-level API (`ChatLanguageModel` + `ToolSpecification`) is currently specified using `ToolParameters` and `JsonSchemaProperty` classes. This API works fine for simple cases, but it does not work well for more complicated cases (e.g., when nested objects or collections or recursion is required).

Moreover, [Structured Outputs](https://github.com/langchain4j/langchain4j/pull/1590) feature is using another API and a lot of logic between tools and structured outputs is duplicated and out of sync.

## Change
`ToolParameters` and `JsonSchemaProperty` classes are now deprecated in favour of new `JsonSchemaElement` API (which is used for Structured Outputs as well). Most of the logic between this 2 features is now unified.

`JsonSchemaElement` represents a schema for a JSON element. It can be of such types:
- `JsonArraySchema`
- `JsonBooleanSchema`
- `JsonEnumSchema`
- `JsonIntegerSchema`
- `JsonNumberSchema`
- `JsonObjectSchema`
- `JsonReferenceSchema`
- `JsonStringSchema`

All model providers that support tools (see the list below) were updated to support the new API. Old API is still supported for backward compatibility, but will be removed in the future.

`ToolSpecifications` helper class now generates `ToolSpecification`s using the new API only.

Example of the new API:
```java
ToolSpecification.builder()
    .name("weather")
    .description("Returns the current weather in the specified city")
    .parameters(JsonObjectSchema.builder()
        .addStringProperty("city", "The name of the city, e.g., Munich")
        .addEnumProperty("units", List.of("CELSIUS", "FAHRENHEIT"))
        .required("city") // the required properties should be specified explicitly
        .build())
    .build();
```

`JsonObjectSchema` builder has some helper methods to make it easier to add properties (e.g., `addProperty`, `addStringProperty`, `addIntegerProperty`, etc.), but properties can also be specified using a map:
```java
ToolSpecification.builder()
    .name("weather")
    .description("Returns the current weather in the specified city")
    .parameters(JsonObjectSchema.builder()
        .properties(Map.of(
            "city", JsonStringSchema.builder().description("The name of the city, e.g., Munich").build(),
            "units", JsonEnumSchema.builder().enumValues("CELSIUS", "FAHRENHEIT").build()
        ))
        .required("city") // the required properties should be specified explicitly
        .build())
    .build();
```

### Providers that support new `JsonSchemaElement` for tools
- [X] Amazon Bedrock
- [X] Anthropic
- [X] Azure OpenAI
- [X] DashScope
- [X] GitHub Models
- [X] Google AI Gemini
- [X] Google Vertex AI Gemini
- [X] Jlama
- [X] LocalAI
- [X] Mistral AI
- [X] Ollama
- [X] OpenAI
- [X] Qianfan
- [X] Zhipu AI

### Tested Providers
- [X] Amazon Bedrock
- [X] Anthropic
- [X] Azure OpenAI
- [X] DashScope
- [X] GitHub Models
- [X] Google AI Gemini
- [X] Google Vertex AI Gemini
- [X] Jlama
- [x] LocalAI
- [X] Mistral AI
- [X] Ollama
- [X] OpenAI
- [X] Qianfan
- [X] Zhipu AI

### Additional Changes
Several bugs have been fixed along the way (see the list of Github issues on the top).

### Breaking changes
- `ToolSpecification.parameters()` method has been renamed into `toolParameters()`

### Potentially breaking changes
- `ToolSpecifications` helper class now generates `ToolSpecification`s with parameters defined using the new API (`JsonObjectSchema`) instead of the old API (`ToolParameters`).
- If `@Tool` does not have a description (`value` annotation attribute), `ToolSpecifications` will return `ToolSpecification` with `description() == null`

## General checklist
- [ ] There are no breaking changes (Most of the use cases should not break)
- [X] I have added unit and integration tests for my change
- [X] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [X] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green
- [X] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

### CODE REVIEW

**Comment by geoand** [comment]
@jmartisk probably something for our branch to track :)

**Comment by langchain4j** [comment]
Hi @tjake!

Some Jlama tests are failing in `JlamaAiServicesWithToolsIT` (in the `use-new-json-schema-for-tools` branch) with such error messages:

```
15:10:25.493 [main] WARN com.github.tjake.jlama.model.AbstractModel -- Tool call detected but no tool call found in response: {"name": "process", "parameters": {"arg0": {"name": "Klaus", "age": 37, "height": 1.78, "married": False}}}

or 

{"name": "process", "parameters": {"arg0": {"name": "Klaus", "age": 37, "height": 1.78, "married": False}}}
```

I am not really sure what is the problem, could you please check?

Thank you! 🙏

**Comment by langchain4j** [comment]
@jiangsier-xyz could you please run all tests in DashScope module (in the `use-new-json-schema-for-tools` branch) and tell me if they pass? 🙏

**Comment by langchain4j** [comment]
@lane12138 and @1402564807, please do the same for Qianfan and Zhipu AI modules respectively🙏 Thanks!

**Comment by jiangsier-xyz** [comment]
> @jiangsier-xyz could you please run all tests in DashScope module (in the `use-new-json-schema-for-tools` branch) and tell me if they pass? 🙏

Could not find artifact dev.ai4j:openai4j:pom:0.23.0
The latest version seems to be 0.22.0:
https://central.sonatype.com/artifact/dev.ai4j/openai4j

**Comment by langchain4j** [comment]
@jiangsier-xyz sorry about that, you can change it to 0.22.0, it should not affect DashScope module

**Comment by jiangsier-xyz** [comment]
> @jiangsier-xyz sorry about that, you can change it to 0.22.0, it should not affect DashScope module

Still have an exception. You may need to deal with JsonReferenceSchema in JsonSchemaElementHelper::toMap.

```text
java.lang.IllegalArgumentException: Unknown type: class dev.langchain4j.model.chat.request.json.JsonReferenceSchema

	at dev.langchain4j.model.chat.request.json.JsonSchemaElementHelper.toMap(JsonSchemaElementHelper.java:243)
	at dev.langchain4j.model.chat.request.json.JsonSchemaElementHelper.toMap(JsonSchemaElementHelper.java:199)
	at dev.langchain4j.model.chat.request.json.JsonSchemaElementHelper.lambda$toMap$1(JsonSchemaElementHelper.java:175)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at java.base/java.util.Collections$UnmodifiableMap.forEach(Collections.java:1553)
	at dev.langchain4j.model.chat.request.json.JsonSchemaElementHelper.toMap(JsonSchemaElementHelper.java:175)
	at dev.langchain4j.model.chat.request.json.JsonSchemaElementHelper.toMap(JsonSchemaElementHelper.java:187)
	at dev.langchain4j.model.chat.request.json.JsonSchemaElementHelper.lambda$toMap$1(JsonSchemaElementHelper.java:175)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at java.base/java.util.Collections$UnmodifiableMap.forEach(Collections.java:1553)
	at dev.langchain4j.model.chat.request.json.JsonSchemaElementHelper.toMap(JsonSchemaElementHelper.java:175)
	at dev.langchain4j.model.chat.request.json.JsonSchemaElementHelper.toMap(JsonSchemaElementHelper.java:187)
	at dev.langchain4j.model.dashscope.QwenHelper.toParameters(QwenHelper.java:391)
	at dev.langchain4j.model.dashscope.QwenHelper.toToolFunction(QwenHelper.java:384)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at dev.langchain4j.model.dashscope.QwenHelper.toToolFunctions(QwenHelper.java:377)
	at dev.langchain4j.model.dashscope.QwenChatModel.generateByNonMultimodalModel(QwenChatModel.java:141)
	at dev.langchain4j.model.dashscope.QwenChatModel.generate(QwenChatModel.java:109)
	at dev.langchain4j.model.dashscope.QwenChatModel.generate(QwenChatModel.java:107)
	at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:229)
	at dev.langchain4j.service.$Proxy69.chat(Unknown Source)
	at dev.langchain4j.service.AiServicesWithNewToolsIT.should_execute_tool_with_pojo_with_recursion(AiServicesWithNewToolsIT.java:320)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

**Comment by langchain4j** [comment]
@jiangsier-xyz thanks for the feedback!

Does DashScope support recursion in json schemas? (`should_execute_tool_with_pojo_with_recursion` should most probably not run for `QwenAiServicesWithToolsIT`, as `supportsRecursion()` returns false by default)

And what about other tests in DashScope module? Do they pass?

**Comment by jiangsier-xyz** [comment]
> @jiangsier-xyz thanks for the feedback!
> 
> Does DashScope support recursion in json schemas? (`should_execute_tool_with_pojo_with_recursion` should most probably not run for `QwenAiServicesWithToolsIT`, as `supportsRecursion()` returns false by default)
> 
> And what about other tests in DashScope module? Do they pass?

The Qwen documentation does not mention support for recursion in json schemas. I recommend not doing this test.

And, other tests all pass after I make a very simple change in DashScope. Do you mind if I commit to this branch?

**Comment by langchain4j** [comment]
@jiangsier-xyz 

> The Qwen documentation does not mention support for recursion in json schemas. I recommend not doing this test.

What do you mean by "not doing this test"? `should_execute_tool_with_pojo_with_recursion` test should not run for DashScope when you run `QwenAiServicesWithToolsIT` It is annotated with `@EnabledIf("supportsRecursion")` and is disabled by default:

```java
    protected boolean supportsRecursion() {
        return false;
    }
```

> And, other tests all pass after I make a very simple change in DashScope. Do you mind if I commit to this branch?

Sure, go ahead, thank you!

**Comment by jiangsier-xyz** [comment]
> @jiangsier-xyz
> 
> > The Qwen documentation does not mention support for recursion in json schemas. I recommend not doing this test.
> 
> What do you mean by "not doing this test"? `should_execute_tool_with_pojo_with_recursion` test should not run for DashScope when you run `QwenAiServicesWithToolsIT` It is annotated with `@EnabledIf("supportsRecursion")` and is disabled by default:
> 
> ```java
>     protected boolean supportsRecursion() {
>         return false;
>     }
> ```

Not sure why it ran. Still checking.
image

**Comment by kpavlov** [comment]
This PR has very long history. Maybe it make sense to split it into multiple small ones?

**Comment by langchain4j** [comment]
@kpavlov indeed, but it is going to be merged this week

**Pull request merged**
