### PR TITLE
fix(TokenUsage): Token can't be null in AI Response

### PR DESCRIPTION
**Pull request by fb33**
Signed-off-by: François Barbe <f.barbe@lectra.com>

## Issue
https://github.com/langchain4j/langchain4j/issues/1294

## Change
add a empty TokenUsage in case of exception in the Response. 

## General checklist

- [ ] There are no breaking changes
- [ ] I have added unit and integration tests for my change
- [ ] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [ ] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for adding new model integration

- [ ] I have added my new module in the [BOM](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-bom/pom.xml)

## Checklist for adding new embedding store integration

- [ ] I have added a `{NameOfIntegration}EmbeddingStoreIT` that extends from either `EmbeddingStoreIT` or `EmbeddingStoreWithFilteringIT`
- [ ] I have added my new module in the [BOM](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-bom/pom.xml)

## Checklist for changing existing embedding store integration

- [ ] I have manually verified that the `{NameOfIntegration}EmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

### CODE REVIEW

**Comment by langchain4j** [comment]
Hi @fb33, thank you!

I guess we should relax the `ensureNotNull(tokenUsage, "tokenUsage")` requirement instead, as not all models return it.
WDYT?

**Comment by fb33** [comment]
@langchain4j yes I'm agree but I've this issue when I tried other type of search than Vector with Azure Ai Search.
Perhaps for other Index DB implementations, the requirement is still relevant ?

**Comment by langchain4j** [comment]
@fb33 sorry, not sure how vector DBs (Index DB) are relevant here?

**Comment by fb33** [comment]
My bad... I mixed topics... my comment makes no sense :) 

So, yes relax the ensureNotNull(tokenUsage, "tokenUsage") requirement is a good option for me.

**Comment by fb33** [comment]
@langchain4j I revert my previous proposal and just relax the requirement as you said.

**Review by ghost — APPROVED** [review]
@fb33 thank you!

**Pull request merged**
