### PR TITLE
Fix #935: DefaultAiService compatibility for TokenUsage result is null

### LINKED ISSUE #935: [BUG] java.lang.NullPointerException - "tokenUsageAccumulator" is null - when using LocalAI function calling
**Describe the bug**

When implementing function calling using LocalAI a NPE is thrown stating "tokenUsageAccumulator" is null

**Log and Stack trace**

```shell
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "dev.langchain4j.model.output.TokenUsage.add(dev.langchain4j.model.output.TokenUsage)" because "tokenUsageAccumulator" is null
        at dev.langchain4j.service.DefaultAiServices$1.invoke(DefaultAiServices.java:175)
        at $Proxy3.chat(Unknown Source)
        at AiServicesFunctionCalling.main(AiServicesFunctionCalling.java:71)
```

**To Reproduce**

Following is the jbang script

```java
//DEPS dev.langchain4j:langchain4j:0.29.1
//DEPS dev.langchain4j:langchain4j-local-ai:0.29.1


import java.time.Duration;
import dev.langchain4j.agent.tool.Tool;
import dev.langchain4j.memory.ChatMemory;
import dev.langchain4j.memory.chat.MessageWindowChatMemory;
import dev.langchain4j.model.chat.ChatLanguageModel;
import dev.langchain4j.model.localai.LocalAiChatModel;
import dev.langchain4j.service.AiServices;

class AiServicesFunctionCalling {

    private static final String MODEL = "gpt-4";
    private static final String BASE_URL = "http://localhost:8080";
    private static final Duration timeout = Duration.ofSeconds(120);
    private static String question;

    static class Calculator {

        @Tool("Calculates the length of a string")
        int stringLength(String s) {
            System.out.println("Called stringLength with s='" + s + "'");
            return s.length();
        }

        @Tool("Calculates the sum of two numbers")
        int add(int a, int b) {
            System.out.println("Called add with a=" + a + ", b=" + b);
            return a + b;
        }

        @Tool("Calculates the square root of a number")
        double sqrt(int x) {
            System.out.println("Called sqrt with x=" + x);
            return Math.sqrt(x);
        }
    }

    interface ChatMinion {
        String chat(String message);
    }

    public static void main(String[] args) {

        ChatLanguageModel model = LocalAiChatModel.builder()
                .baseUrl(BASE_URL)
                .modelName(MODEL)
                .timeout(timeout)
                .temperature(0.0)
                .build();
        ChatMemory memory = MessageWindowChatMemory.withMaxMessages(10);

        ChatMinion minion = AiServices.builder(ChatMinion.class)
                .chatLanguageModel(model)
                .tools(new Calculator())
                .chatMemory(memory)
                .build();
        question = "What is the square root 226?";
        System.out.println("Asking question: " + question);
        String text = minion.chat(question);
        System.out.println("\n\nResponse:\n\n" + text);
    }
}
```

**Expected behavior**

Should call the function and return the result

**Please complete the following information:**
- LangChain4j version: 0.29.1
- LLM(s) used: LocalAI (gpt-4)
- Java version: 21
- Spring Boot version (if applicable): NA 

**Additional context**

### PR DESCRIPTION
**Pull request by Kugaaa**
## Context
See [#935](https://github.com/langchain4j/langchain4j/issues/935)
`LocalAiChatModel.generate` the response of generate returned that tokenUsage is null

## Change
- LocalAiChatModel tried to return TokenUsage result
- TokenUsage.add return if origin token usage is null, ensure `AiService` proxy successfully executed

## Checklist
Before submitting this PR, please check the following points:
- [x] I have added unit and integration tests for my change
- [x] All unit and integration tests in the module I have added/changed are green
- [x] All unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules are green
- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added my new module in the [BOM](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-bom/pom.xml) (only when a new module is added)

## Checklist for adding new embedding store integration
- [ ] I have added a {NameOfIntegration}EmbeddingStoreIT that extends from either EmbeddingStoreIT or EmbeddingStoreWithFilteringIT

### CODE REVIEW

**Comment by langchain4j** [comment]
@Kugaaa thank you, but this has been fixed already by another PR: https://github.com/langchain4j/langchain4j/pull/939

**Comment by ohadpinch** [comment]
@Kugaaa @langchain4j Need to consider that fix, it worked for me

**Comment by langchain4j** [comment]
@ohadpinch you mean fix in this (closed) PR?

**Comment by ohadpinch** [comment]
Yes

**Comment by Kugaaa** [comment]
I merged the origin/main
And [this commit](https://github.com/langchain4j/langchain4j/pull/942/commits/fa130ed814387e0af95a0e276b6a181c8b7f64a6) handle the OpenAi SDK return a `Usage` is null, a NPE may be thrown after the toolSpecifications generate.

pertinent code
- dev/langchain4j/service/DefaultAiServices.java:128
- dev/langchain4j/service/DefaultAiServices.java:172

**Comment by langchain4j** [comment]
@Kugaaa thank you a lot!
Hovewer, I went with another approach: https://github.com/langchain4j/langchain4j/pull/1119
I am not sure it is correct to return `TokenUsage` with `null` values inside. If there is no token usage information, `null` should be returned instead of `TokenUsage.from(null, null, null)` imho

**Pull request closed without merging**
