### PR TITLE
PGVector: First E2E implementation (Java 8 Implementation)

### PR DESCRIPTION
**Pull request by kevin-wu-os**
# Summary

I use https://github.com/pgvector/pgvector-java/ to implement `PgVectorEmbeddingStore`. 

1. Insertion works as regular SQL as long as a table (with namespace as table name) contains type `vector`.
2. Query is upon the enhanced SQL by vector extension. The SQL returned results are the final result with passing `minScore` and `maxResults`.

# Caveat
* The implementation leaves responsibility of installing `vector` extension to users.
* Only cosine similarity is used.
* Only ivfflat index is used.
* I only have Java 17 on my machine and my priority 1 was to unblock my work. Now I am here to contribute. Let me know if it is a concern.

# Test
_Test Class with connection to compatible vector instance_
Screen Shot 2023-10-18 at 10 16 59 PM

_Test Class with local container provided by same author in pgvector-java_
**Additional Test to ensure the container is running**
Screen Shot 2023-10-18 at 10 17 20 PM

### CODE REVIEW

**Comment by IrynaLiubarska** [comment]
Hi @kevin-wu-os, thank you for your contribution! At present, we intend to maintain compatibility with Java 8, given that approximately 30% of developers are still using either Java 8 or Java 11. We believe it is important for the library to remain backward compatible

**Comment by kevin-wu-os** [comment]
@IrynaLiubarska - I did a quick look. `formatted` is probably the only feature with 15+ feature. I can install Java 8 and try later. Let me know if you see something else.

**Comment by kevin-wu-os** [comment]
It is now Java 8 compatible. See tests and the version used.
Screen Shot 2023-10-19 at 9 06 55 PM
Screen Shot 2023-10-19 at 9 03 38 PM

**Review by ghost — APPROVED** [review]
@kevin-wu-os thanks a lot!

**Pull request merged**
