### PR TITLE
[FEATURE] Remove transitive log4j dependency from langchain4j-documen…

### LINKED ISSUE #832: [FEATURE] Remove transitive log4j dependency from langchain4j-document-parser-apache-tika module
To get rid of annoying log:
`ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
`

### PR DESCRIPTION
**Pull request by oscerd**
…t-parser-apache-tika module

## Context
Fixes #832 

## Change
I removed the transitive dependency log4j-api from tika-parsers-standard-package

and added explicit dependency to log4j-api, log4j-core and log4j-slf4j2-impl, like done for document-loader github and document-loader azure storage blob.

I don't think a unit/integration test is required for this.

## Checklist
Before submitting this PR, please check the following points:
- [ ] I have added unit and integration tests for my change
- [ ] All unit and integration tests in the module I have added/changed are green
- [ ] All unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules are green
- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added my new module in the [BOM](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-bom/pom.xml) (only when a new module is added)

## Checklist for adding new embedding store integration
- [ ] I have added a {NameOfIntegration}EmbeddingStoreIT that extends from either EmbeddingStoreIT or EmbeddingStoreWithFilteringIT

### CODE REVIEW

**Comment by oscerd** [comment]
Can we run the test on CI please? Thanks.

**Comment by langchain4j** [comment]
@oscerd will it work for the user without test deps? I tried at some point and it did not work...

**Comment by oscerd** [comment]
It should, but I can have a second try

**Comment by oscerd** [comment]
Do you want me to remove completely the test dependencies? For me it is working fine.

**Comment by langchain4j** [comment]
If I just add exclusion (without adding test dependencies, this is what I get in tests:
```
[ERROR] Errors: 
[ERROR]   ApacheTikaDocumentParserTest.should_parse_doc_ppt_and_pdf_files:30 » NoClassDefFound Could not initialize class org.apache.poi.poifs.filesystem.POIFSFileSystem
[ERROR]   ApacheTikaDocumentParserTest.should_parse_doc_ppt_and_pdf_files:30 » NoClassDefFound Could not initialize class org.apache.poi.poifs.filesystem.POIFSFileSystem
[ERROR]   ApacheTikaDocumentParserTest.should_parse_xls_files:46 » NoClassDefFound org/apache/logging/log4j/LogManager
[INFO] 
[ERROR] Tests run: 11, Failures: 5, Errors: 3, Skipped: 0
```
So it seems that we have to live with it...

**Comment by oscerd** [comment]
Yes, it seems so.

**Comment by langchain4j** [comment]
@oscerd I will close this PR and issue then

**Comment by oscerd** [comment]
Sure. Thanks.

**Pull request closed without merging**
