### PR TITLE
#1636 add lombok annotation processor

### PR DESCRIPTION
**Pull request by kpavlov**
## Issue

The JDK23 build is Red 🟥 , because Lombok annotation processor is not configured as required.

## Change

🟢 The build is green
[Enable Lombok annotation processor](https://projectlombok.org/setup/maven) to make the build green under JDK23

## General checklist

- [x] There are no breaking changes
- [ ] I have added unit and integration tests for my change
- [ ] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [ ] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for adding new maven module

- [ ] I have added my new module in the root `pom.xml` and `langchain4j-bom/pom.xml`

## Checklist for adding new embedding store integration

- [ ] I have added a `{NameOfIntegration}EmbeddingStoreIT` that extends from either `EmbeddingStoreIT` or `EmbeddingStoreWithFilteringIT`
- [ ] I have added a `{NameOfIntegration}EmbeddingStoreRemovalIT` that extends from `EmbeddingStoreWithRemovalIT`

## Checklist for changing existing embedding store integration

- [ ] I have manually verified that the `{NameOfIntegration}EmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

### CODE REVIEW

**Comment by kpavlov** [comment]
@langchain4j , let's make "Java CI / java_build" required for PRs after merging this one

**Comment by kpavlov** [comment]
#2107 is discovered

**Review by ghost — APPROVED** [review]
@kpavlov thanks a lot!

**Comment by langchain4j** [comment]
> @langchain4j , let's make "Java CI / java_build" required for PRs after merging this one

Currently, the following checks are required: `compliance`, `java_build (17)` and `java_build (21)`. I will include `java_build (23)`

**Comment by langchain4j** [comment]
I've also added:
- Codacy Static Code Analysis
- upload-patch

**Pull request merged**
