### PR TITLE
 [BUG] Nightly and release jobs should not be run on fork repositories #1302

### PR DESCRIPTION
**Pull request by Wadimz**
This change addresses issue described in bug:  [BUG] Nightly and release jobs should not be run on fork repositories #1302 
Change was verified on fork using fork repository path.

## Issue
https://github.com/langchain4j/langchain4j/issues/1302

## Change
Change adds github job condition to be run only on the main project's repository.

## General checklist

- [x] There are no breaking changes
- [x] I have added unit and integration tests for my change
- [x] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [x] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for adding new model integration

- [ ] I have added my new module in the [BOM](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-bom/pom.xml)

## Checklist for adding new embedding store integration

- [ ] I have added a `{NameOfIntegration}EmbeddingStoreIT` that extends from either `EmbeddingStoreIT` or `EmbeddingStoreWithFilteringIT`
- [ ] I have added my new module in the [BOM](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-bom/pom.xml)

## Checklist for changing existing embedding store integration

- [ ] I have manually verified that the `{NameOfIntegration}EmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

### CODE REVIEW

**Review by ghost — APPROVED** [review]
@Wadimz thank you!

**Comment by langchain4j** [comment]
Hi @Wadimz, both snapshot buildes are failing, seems to be right after this PR was merged:
- https://github.com/langchain4j/langchain4j/actions/workflows/snapshot_release.yaml
- https://github.com/langchain4j/langchain4j/actions/workflows/snapshot_release_core_and_parent.yaml

Could you please check?

**Comment by langchain4j** [comment]
BTW I've added this: https://github.com/langchain4j/langchain4j/commit/071004b9886904f8830bd2ba6bb1f5196025383c

**Comment by Wadimz** [comment]
Absolutely, checking

**Comment by Wadimz** [comment]
Suspicious that only this module started failing with 401. 
`[INFO] LangChain4j :: Experimental :: SQL ................. FAILURE [  1.757 s]`
Might it be some expired token here?
```
 Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.13:deploy (injected-nexus-deploy) on project ***-experimental-sql: Failed to deploy artifacts: Could not transfer artifact dev.***:***-pinecone:jar:sources:0.32.0-20240617.095335-57 from/to ossrh (https://s01.oss.sonatype.org/content/repositories/snapshots): authentication failed for https://s01.oss.sonatype.org/content/repositories/snapshots/dev/***/***-pinecone/0.32.0-SNAPSHOT/***-pinecone-0.32.0-20240617.095335-57-sources.jar, status: 401 Content access is protected by token -> [Help 1]
```

**Comment by langchain4j** [comment]
It seems to fail on the attempt to upload the first artifact

**Comment by langchain4j** [comment]
I guess I know the reason... Maven central are making changes to the OSSRH authentication backend. I will have to change the authentication from user/pwd to token.

Sorry for bothering you, I wrongly assumed that it is because of this PR due to the timing...

**Comment by Wadimz** [comment]
Thanks for quick investigation!

**Pull request merged**
