### PR TITLE
Initialize the LangChain4j GitHub Bot config files

### PR DESCRIPTION
**Pull request by gsmet**
As discussed :).

### CODE REVIEW

**Review by ghost — APPROVED** [review]
@gsmet thank you so much!

**Comment by langchain4j** [comment]
cc @jdubois @agoncal Azure issues/PRs will now be automatically tagged and you will be notified!

Thanks to @gsmet :)

**Comment by agoncal** [comment]
That is so cool !!! Thanks

**Comment by glaforge** [comment]
I'd be interested in being tagged for Gemini and Vertex AI issues (ie. the `vertex-ai` and `vertex-ai-gemini` modules)

**Comment by langchain4j** [comment]
@glaforge sure, let me add config for that!

**Comment by gsmet** [comment]
For the record, the config file is here:
- https://github.com/langchain4j/langchain4j/blob/main/.github/langchain4j-github-bot.yml

And the format is described in details here:
- https://github.com/langchain4j/langchain4j-github-bot

**Pull request merged**
