### PR TITLE
enable userAgentSuffix in azure open ai

### PR DESCRIPTION
**Pull request by KaiqianYang**
## Change
enabled to append userAgent suffix in InternalAzureOpenAiHelper
added the userAgentSuffix argument in the azure open ai model classes

## General checklist

- [x] There are no breaking changes
- [ ] I have added unit and integration tests for my change
- [x] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [ ] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for adding new model integration

- [ ] I have added my new module in the [BOM](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-bom/pom.xml)

## Checklist for adding new embedding store integration

- [ ] I have added a `{NameOfIntegration}EmbeddingStoreIT` that extends from either `EmbeddingStoreIT` or `EmbeddingStoreWithFilteringIT`
- [ ] I have added my new module in the [BOM](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-bom/pom.xml)

## Checklist for changing existing embedding store integration

- [ ] I have manually verified that the `{NameOfIntegration}EmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

### CODE REVIEW

**Comment by langchain4j** [comment]
Hi @KaiqianYang how is this different from https://github.com/langchain4j/langchain4j/pull/1287?

**Comment by KaiqianYang** [comment]
> Hi @KaiqianYang how is this different from #1287?

Hi @langchain4j

I work with @showpune who is owner of [1287](https://github.com/langchain4j/langchain4j/pull/1287).  My PR incorporates the change in [1287](https://github.com/langchain4j/langchain4j/pull/1287) and applies it to more models. It also updates the tests accordingly. Additionally, I updated the variable name from `appendUserAgent(String)` to `userAgentSuffix(String)`

**Comment by langchain4j** [comment]
@KaiqianYang oh, I see. I missed that it is actually a suffix, not a complete user agent. How will this be used?

**Comment by KaiqianYang** [comment]
> @KaiqianYang oh, I see. I missed that it is actually a suffix, not a complete user agent. How will this be used?

@langchain4j by configuring a custom userAgentSuffix, such as a suffix like `langchain4j-azure-open-ai-spring-boot` in the langchain4j-azure-open-ai-spring-boot-starter, it becomes possible to distinguish the requests made to Azure Open AI through different libraries. This allows for the track of library usage. Furthermore, incorporating a version number into the suffix enables the tracking of usage of different library versions.

**Comment by langchain4j** [comment]
@KaiqianYang ok, it is clear with the spring boot starter. But it is not very clear with the version, do you expect users to set it?

**Comment by KaiqianYang** [comment]
> @KaiqianYang ok, it is clear with the spring boot starter. But it is not very clear with the version, do you expect users to set it?

@langchain4j the purpose of this PR is **for the scenario of spring boot starter**. As for the possibility of giving details like version number, it's mentioned just because Julien mentioned it in comment of [1287](https://github.com/langchain4j/langchain4j/pull/1287). How about just focusing on the scenario of spring boot starter? 🙂

**Review by ghost — APPROVED** [review]
@KaiqianYang thank you!

**Pull request merged**
