### PR TITLE
Updating index is not mandatory to create AzureAISearchContentRetriver

### PR DESCRIPTION
**Pull request by showpune**
## Context
To create a AzureAISearchContentRetriver, updating index is not mandatory

## Change

- Add createOrUpdateIndex in AzureAiSearchEmbeddingStore
- AzureAISearchContentRetriver can be build with dimension and index

## Checklist
Before submitting this PR, please check the following points:
- [ ] I have added unit and integration tests for my change
- [X] All unit and integration tests in the module I have added/changed are green
- [ ] All unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules are green
- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added my new module in the [BOM](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-bom/pom.xml) (only when a new module is added)

### CODE REVIEW

**Comment by langchain4j** [comment]
@showpune there are conflicts now, could you please check?

**Comment by showpune** [comment]
@jdubois , can you help to check?

**Comment by langchain4j** [comment]
@jdubois could you please check? I would love to merge it before making a release today (in few hours)

**Comment by jdubois** [comment]
@langchain4j I'm not it right now! I think I found another bug will doing this...

**Comment by jdubois** [comment]
@langchain4j can you close this PR? As I don't have write access to this PR, I will create a new one

**Pull request closed without merging**
