### PR TITLE
Anthropic: Support tools (#897)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by langchain4j** [comment]
@geoand fyi

**Review by geoand — APPROVED** [review]
Thanks!

**Comment by geoand** [comment]
With this change I can now get tools working properly in Quarkus!

Thanks so much for the immediate reaction!

**Comment by langchain4j** [comment]
@geoand No problem, just in time for the new release :)

**Comment by geoand** [comment]
🥳

**Pull request merged**
