### PR TITLE
[FEATURE] Tool method support user defined class

### PR DESCRIPTION
**Pull request by huangkunyhx**
Tool method support user defined class

### New Features

- Modified annotation P to support fields in user-defined classes
- The TOOL method supports custom classes

### usage
```java
public class User {
    private String name;
    @P("password")
    private String password;
}
```

```
@Tool({"tool"})
public int f(@P("user info") User user);
```

### CODE REVIEW

**Comment by langchain4j** [comment]
Hi @huangkunyhx thanks a lot!

There are already these PRs that seem to have overlapping functionality:
https://github.com/langchain4j/langchain4j/pull/708
https://github.com/langchain4j/langchain4j/pull/941

Could you please check?

**Comment by huangkunyhx** [comment]
> Hi @huangkunyhx thanks a lot!
> 
> There are already these PRs that seem to have overlapping functionality: #708 #941
> 
> Could you please check?

Hi  @langchain4j
Thank you for your feedback.

The structure of the generated tool function in 708 utilizes ‘schema’ to define fields within classes, whereas I have been employing ‘properties’. My attempts to access OpenAI using the ‘schema’ approach haveyielded no results. Furthermore, when the parameter is of type List<POJO>, a Gson type conversion exception is also prompted.

**Comment by huangkunyhx** [comment]
> Hi @huangkunyhx thanks a lot!
> 
> There are already these PRs that seem to have overlapping functionality: #708 #941
> 
> Could you please check?

Hi @langchain4j
Thank you for your feedback.

The structure of the generated tool function in #708  uses ‘schema’ to define fields within classes, whereas I use ‘properties’. I tried to  access OpenAI using the ‘schema’ method but got no results. Furthermore, when the parameter is of type List, a Gson type conversion exception is also prompted.`ClassCastException: class com.google.gson.internal.LinkedTreeMap cannot be cast to class`

**Comment by langchain4j** [comment]
@huangkunyhx was this closed by mistake?

**Pull request closed without merging**
