### PR TITLE
langchain4j-vespa refactor

### LINKED ISSUE #1681: Vespa: migrate from Gson to Jackson
Migrate `langchain4j-vespa` module from Gson to Jackson.
Apart from `converter-gson`, `VespaEmbeddingStore` uses `Json.toJson()` and `Json.toInputStream()` methods that uses Gson under the hood.

### PR DESCRIPTION
**Pull request by Martin7-1**
## Issue

Closes #1681 

## Change

1. Raise the baseline from jdk8 to jdk17 (because the newest `vespa-feed-client` is no longer support jdk8).
2. Migrate from Gson to Jakson.
3. Get rid of lombok
4. Implement `VespaEmbeddingStoreIT` and `VespaEmbeddingStoreCloudIT`

## General checklist

- [ ] There are no breaking changes
- [ ] I have added unit and integration tests for my change
- [ ] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [ ] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for adding new model integration

- [ ] I have added my new module in the [BOM](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-bom/pom.xml)

## Checklist for adding new embedding store integration

- [ ] I have added a `{NameOfIntegration}EmbeddingStoreIT` that extends from either `EmbeddingStoreIT` or `EmbeddingStoreWithFilteringIT`
- [ ] I have added my new module in the [BOM](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-bom/pom.xml)

## Checklist for changing existing embedding store integration

- [ ] I have manually verified that the `{NameOfIntegration}EmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

### CODE REVIEW

**Comment by langchain4j** [comment]
@Martin7-1 thank you!
The description says 

> Implement VespaEmbeddingStoreIT and VespaEmbeddingStoreCloudIT

But I can only see `VespaEmbeddingStoreCloudIT` in the PR, could you please check?

**Comment by Martin7-1** [comment]
> But I can only see VespaEmbeddingStoreCloudIT in the PR, could you please check?

It's a draft PR and still have some TODO (including implement `VespaEmbeddingStoreIT`). Because I'm not familiar with Vespa, @Heezer will take this PR over.

**Comment by Heezer** [comment]
There is no vespa support on testcontainers: https://testcontainers.com/modules/?category=vector-database 😞 @langchain4j any experience adding a new one to testcontainers?

**Comment by Martin7-1** [comment]
> There is no vespa support on testcontainers: https://testcontainers.com/modules/?category=vector-database 😞 @langchain4j any experience adding a new one to testcontainers?

Vespa has [official docker image](https://hub.docker.com/r/vespaengine/vespa/). Maybe you can use it and `GenericContainer` to create one.

**Comment by Heezer** [comment]
> Vespa has [official docker image](https://hub.docker.com/r/vespaengine/vespa/). Maybe you can use it and `GenericContainer` to create one.

yes, already looking into this 😄 thanks

**Comment by langchain4j** [comment]
@Heezer, could you please implement `search()` method in scope of this PR?
Should be very easy, something like [this](https://github.com/langchain4j/langchain4j/commit/75c0458e63683660720b9e6877649aa85102a0a3). 🙏

**Comment by Heezer** [comment]
> @Heezer, could you please implement `search()` method in scope of this PR?
> Should be very easy, something like [this](https://github.com/langchain4j/langchain4j/commit/75c0458e63683660720b9e6877649aa85102a0a3). 🙏 

Yes, straight after I get local dockerized Vespa working 😀 I'm still on it.

**Comment by Heezer** [comment]
@Martin7-1 , @langchain4j guys, I've created #2056, only one point is open there CloudIT, but the rest (most functionality and lots of refactorings, see the full list of changes) is there.

**Comment by langchain4j** [comment]
Closing in favour of https://github.com/langchain4j/langchain4j/pull/2056

@Martin7-1 thank you for your initial work!

**Pull request closed without merging**
