### PR TITLE
Make DefaultAiServices public

### PR DESCRIPTION
**Pull request by vladislavkn**
## Issue

Scope: `package dev.langchain4j.service`

Currently, the DefaultAiServices class is not publicly accessible, limiting its usability for libraries built on langchain4j. Developers are restricted to using the standard building method of AiServices that selects some factory method for creating AI services, which may not align with lbraries specific architectural needs. This restricts flexibility and reusability in extending AI services functionality.

## Change
This merge request changes the visibility of the DefaultAiServices class to public. By doing so, it allows libraries that are built upon langchain4j to directly utilize the default AI services builder instead of relying solely on the random factory method.

## General checklist

- [x] There are no breaking changes
- [x] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [x] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [x] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)

### CODE REVIEW

**Comment by langchain4j** [comment]
@vladislavkn thank you!

What do you mean by "random factory method"?

**Comment by vladislavkn** [comment]
"Random" is not the best matching word. I've meant that another library, e.g. [quarkus-langchain4j](https://github.com/quarkiverse/quarkus-langchain4j) can implement an aiService factory method that differs from the default (`DefaultAiServices`). In this case the creation of the aiServices in the way described in the [langchain4j docs](https://docs.langchain4j.dev/tutorials/ai-services/#simplest-ai-service) can not work: in the example with quarkus-langchain4j the aiService interface must be additionally annotated with `CreatedAware`. Sometimes this requirement cannot be satisfied, e.g. when the aiService is initiated inside of another library that works with "pure" langchain4j. 

This PR is intended to provide a way to such libraries to explicitly select the DefaultAiServices method of creation of aiServices.

Please check if it is still unclear or if the usecase described can be fixed in another way. Thank you for you help 🙂

**Comment by langchain4j** [comment]
> I've meant that another library, e.g. [quarkus-langchain4j](https://github.com/quarkiverse/quarkus-langchain4j) can implement an aiService factory method that differs from the default (DefaultAiServices)

This is how it is done now, no? Quarkus extension has it's own implementation.

> In this case the creation of the aiServices in the way described in the [langchain4j docs](https://docs.langchain4j.dev/tutorials/ai-services/#simplest-ai-service) can not work

AFAIK in Quarkus extension one is not supposed to create AI service programmaticaly. @geoand could you please comment?

> Please check if it is still unclear or if the usecase described can be fixed in another way.

Yes, please expand a bit, I am still not sure I understand the use case. An example would be very helpful.

**Comment by geoand** [comment]
> AFAIK in Quarkus extension one is not supposed to create AI service programmaticaly. @geoand could you please comment?

There is actually some wizardry to make it work :)

**Comment by vladislavkn** [comment]
> Yes, please expand a bit, I am still not sure I understand the use case. An example would be very helpful.

I'm working on a Java library for model quality evaluation, similar to Ragas. It currently uses only Langchain4j, not the Quarkus extension. Although still in development and internal testing, the library is expected to be open-sourced.

The core library has evaluators that work with LLMs. An example constructor looks like:

```java
public FaithfulnessEvaluator(ChatLanguageModel model) {
    bot = AiServices.create(FaithfulnessBot.class, model);
}
```

Here, `FaithfulnessBot` is just an interface as described in Langchain4j docs.

I want to use the library in a production project that uses Quarkus and Quarkus-Langchain4j. When creating a `FaithfulnessEvaluator` instance in the project, I get an error during `aiService` creation:

```java
@Inject
public Metrics(ChatLanguageModel chatLanguageModel, EmbeddingModel embeddingModel) {
    faithfulness = new FaithfulnessEvaluator(chatLanguageModel);
    // ...
}
```

The error:

```
java.lang.RuntimeException: Quarkus was not able to determine class 'dev.rage4j.evaluation.faithfulness.FaithfulnessBot' as an AiService at build time. Consider annotating the class with '@CreatedAware'
```

To avoid this error I wanted to use the `DefaultAiServices` class for the creation of the aiServices.

I want to keep the library core as clean and small as possible and the question is whether there is better way to integrate the library in the Quarkus project?

**Comment by geoand** [comment]
A very simple thing to try is to add an empty `META-INF/beans.xml` file to your library which should make Quarkus aware of the code in it.

**Comment by vladislavkn** [comment]
> A very simple thing to try is to add an empty META-INF/beans.xml file to your library which should make Quarkus aware of the code in it.

Thank you very much, I will try it!

**Comment by geoand** [comment]
Let me know how it goes :)

**Comment by vladislavkn** [comment]
It seems to work, thank you for the solution. I think that the PR can be closed.

**Pull request closed without merging**
