### PR TITLE
langchain4j-ollama get rid of lombok

### LINKED ISSUE #1636: [FEATURE] Get rid of Lombok
Rewrite lombok-generated code and get rid of lombok dependency.

### PR DESCRIPTION
**Pull request by Martin7-1**
## Issue
#1636 

## Change
`langchain4j-ollama` get rid of `lombok`

## General checklist

- [x] There are no breaking changes
- [ ] I have added unit and integration tests for my change
- [x] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [x] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

### CODE REVIEW

**Comment by Martin7-1** [comment]
image

@langchain4j Hi! It seems that `langchain4j-ollama` need a huge amount of disk space to build the docker image, and the Github Action will fail due to it. Any solution about it?

**Comment by langchain4j** [comment]
@Martin7-1 probably running tests locally for the time being...

**Comment by Martin7-1** [comment]
@langchain4j Hi! This PR is ready for review. All tests are green in my local environment.

**Comment by langchain4j** [comment]
@Martin7-1 `should_execute_a_tool_then_answer` is failing, seems that tools are not serialized properly:

```json
{
  "model" : "mistral",
  "messages" : [ {
    "role" : "user",
    "content" : "What is the weather today in Paris?"
  } ],
  "options" : { },
  "stream" : false,
  "tools" : [ {
    "type" : "function",
    "function" : { }
  } ]
}
```

**Review by ghost — APPROVED** [review]
@Martin7-1 thank you!

**Pull request merged**
