### PR TITLE
Observability: Updated model listener API to be more integration friendly

### PR DESCRIPTION
**Pull request by ghost**
## Issue
[ModelListener](https://github.com/langchain4j/langchain4j/pull/1058) does not allow passing data between methods of the same listener or between multiple listeners.

## Change
- added attributes to allow passing data between listener methods or multiple listeners
- changed generic model listener to model-specific listener

## General checklist
- [ ] There are no breaking changes
- [X] I have added unit and integration tests for my change
- [X] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [X] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green
- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)

### CODE REVIEW

**Comment by langchain4j** [comment]
@geoand could you please review?

**Review by geoand — APPROVED** [review]
Seems perfectly reasonable to me

**Comment by langchain4j** [comment]
@geoand that was fast 😅 Thank you!

**Comment by geoand** [comment]
YW :)

**Pull request merged**
