### PR TITLE
Add docusaurus-lunr-search plugin

### PR DESCRIPTION
**Pull request by InAnYan**
## Issue
[https://github.com/langchain4j/langchain4j/issues/1219](https://github.com/langchain4j/langchain4j/issues/1219)

## Change
Added the `docusaurus-lunr-search` plugin.

It may seem that for search feature we would need a server. But nothing stops us from passing that logic to the client)

So, if the index for pages is not too big, we will delegate the search functionality to client. That's what this plugin does (I think).

It works with `npm run serve`, but I couldn't test it with just opening the `index.html` file.

Oh, I'm sorry, my editor autoformatted the file)

## General checklist

- [x] There are no breaking changes
- [ ] I have added unit and integration tests for my change
- [ ] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green
- [ ] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)

### CODE REVIEW

**Comment by InAnYan** [comment]
@langchain4j Would be very nice, instead of using crappy Google.

Hope this won't be a big problem to test this plugin. It works locally, I hope it will work on GitHub static websites

**Review by ghost — APPROVED** [review]
@InAnYan thanks! Let's try to deploy it...

**Comment by InAnYan** [comment]
@langchain4j Is it deployed?

I remember having it run locally and it (search bar or button) was in the upper right corner

**Comment by langchain4j** [comment]
@InAnYan deployed, seems to be working, thank you! 🤗

**Comment by LizeRaes** [comment]
Wow smashing, works super fast. Thanks a lot!!!

**Pull request merged**
