### PR TITLE
Add ModelAware interface

### PR DESCRIPTION
**Pull request by alesj**
Would something like this make sense?
If yes, it can be added on all model impls that support this ...

### CODE REVIEW

**Comment by alesj** [comment]
@geoand ^ ?

**Comment by geoand** [comment]
I think it makes sense, WDYT @langchain4j ?

**Comment by langchain4j** [comment]
Totally makes sense, hovewer I was considering exposing not only model name, but also other parameters (e.g., `temperature`, `maxOutputTokens`, etc. All of parameters listed [here](https://github.com/langchain4j/langchain4j/pull/1989/files#diff-0eccc7b5695d9afff5fe62c8faba2e7994cdb4f6f9750d88877799827c6308f0R21) in `ChatRequest` class) that can be configured when `ChatLanguageModel` is created. WDYT?

**Comment by glaforge** [comment]
I agree we should also standardize on some other parameters, to have consistent naming conventions for the builders instantiating our models. 
Should we have one interface, or maybe even one for each parameter? Say, interfaces like `HasModelName`, `HasTopP`, etc?

**Comment by langchain4j** [comment]
Yes, maybe something like:
```java
public interface ChatParameters {

    String modelName();
    Double temperature();
    ...
}

public interface ChatLanguageModel {

    ...
    
    ChatParameters parameters();
}

public interface ChatRequest {

    ...
    
    ChatParameters parameters();
}
```

**Comment by langchain4j** [comment]
These model parameters will be required (as a group) in multiple cases:
- Default model parameters:
  - specify default model parameters when creating `ChatModel` instance (what @glaforge is suggesting, to standartize it)
  - specify default model parameters when creating `ChatModel` with one's custom model classes (discussed today with @mariofusco)
  - get default model parameters from `ChatModel` instance (addressed by this PR)
- Request-specific model parameters:
  - specify request-specific model parameters when creating `ChatRequest` with builder
  - specify request-specific model parameters when creating `ChatRequest` with one's custom model classes (discussed today with @mariofusco)
  - get request-specific model parameters from `ChatRequest` instance

This is also required for implementing `ObservableChatModel` (to have a common observability logic for all models).

@alesj I hope this PR is not urgent? I would like to take a bit of time (a few days) to play with this idea in scope of https://github.com/langchain4j/langchain4j/pull/1989 and see how to better implement it so that there is a uniform API for all those cases mentioned above.

Thanks for the very timely PR BTW :)

**Comment by alesj** [comment]
@langchain4j nah no rush.
I just wanted to get this rolling, as I think it was useful.

e.g. what about also (Chat)Response (or any type of response, as there are already a few) having this as well?

As this would ease things with something like
* https://github.com/quarkiverse/quarkus-langchain4j/pull/1138
(this is where the need for this PR came from ...)

**Comment by langchain4j** [comment]
@alesj could you please clarify regarding response/token usage?
Right now `ChatResponse` returns `TokenUsage` which has unified input/output tokens.

Regarding `Response` classes:
- `Response<T>` will be removed soon, each type of model (e.g., chat, embedding, image, etc) will return it's own response type.
- `ChatModelResponse` will be removed as well, `ChatModelListener` will operate with `ChatResponse`.

So at the end there will be a single response class for each type of model: `ChatResponse`, `EmbeddingResponse`, `ImageResponse`, etc.

**Comment by alesj** [comment]
> @alesj could you please clarify regarding response/token usage?

I would also need a model type in the response -- which is only available atm in `ChatModelResponse` (all other response types currently don't have it).
(other params - from the discussion above - might also come in handy sometime in the future, you never know :-)

**Comment by langchain4j** [comment]
@alesj 

> I would also need a model type in the response -- which is only available atm in ChatModelResponse (all other response types currently don't have it).
> (other params - from the discussion above - might also come in handy sometime in the future, you never know :-)

By "model type in the response" do you mean model name/id (e.g., `gpt-4o-mini-2024-07-18`)?
`ChatResponse` will have `modelName` after https://github.com/langchain4j/langchain4j/pull/1989 is merged. Every `ChatLanguageModel` implementation will eventually provide it if it is available in the API response.

**Comment by alesj** [comment]
> By "model type in the response" do you mean model name/id (e.g., gpt-4o-mini-2024-07-18)?

Yes.
Something I can match from their pricing website. :-)

**Comment by langchain4j** [comment]
@alesj please check the description of https://github.com/langchain4j/langchain4j/pull/1989, everything that you've described should be available in the new API.
Thus I am closing this PR. Thank you for opening this discussion, it helped a lot!

**Pull request closed without merging**
