### PR TITLE
[FEATURE] Add DuckDB EmbeddingStore implementation (#2183)

### LINKED ISSUE #2183: [FEATURE] Add support to use DuckDB as EmbeddingStore
[DuckDB](https://duckdb.org/) is a great in-process database that allows vector search. Using it as an EmbeddingStore will allow storing embeddings both in-memory and in a file with good performances.

### PR DESCRIPTION
**Pull request by fb64**
## Issue

Closes #2183

## Change

Add implementation of EmbeddingStore with Duckdb that supports metadata.

## General checklist

- [x] There are no breaking changes
- [x] I have added unit and integration tests for my change
- [x] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [x] I have manually run all the unit and integration tests in the [[core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core)](https://github.com/langchain4j/langchain4j/tree/[main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j)/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [x] I have added/updated the [[documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ]  I have added an example in the [[examples repo](https://github.com/langchain4j/langchain4j-examples)](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ]  I have added/updated [[Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for adding new maven module

- [x] I have added my new module in the root `pom.xml` and `langchain4j-bom/pom.xml`

## Checklist for adding new embedding store integration

- [x] I have added a `{NameOfIntegration}EmbeddingStoreIT` that extends from either `EmbeddingStoreIT` or `EmbeddingStoreWithFilteringIT`
- [x] I have added a `{NameOfIntegration}EmbeddingStoreRemovalIT` that extends from `EmbeddingStoreWithRemovalIT`

### CODE REVIEW

**Comment by kpavlov** [comment]
Thank you, @fb64 . @langchain4j , shouldn't it be adopted in the community modules repo?

**Comment by langchain4j** [comment]
@kpavlov right, I keep forgetting about that, thanks!

@fb64 thank you so much for your contribution! Could you please re-open this PR against https://github.com/langchain4j/langchain4j-community?

**Comment by fb64** [comment]
Yes, I didn't see anything about community repo  in the contributing documentation that's why I created the PR here.
But yes, no problem I can re-open it in the community repo.

**Comment by fb64** [comment]
@langchain4j should I re-create the issue #2183 on https://github.com/langchain4j/langchain4j-community as well ?

**Comment by langchain4j** [comment]
@fb64 sorry for the confusion. This is pretty new thing, I will update the contribution guide.
No need to create another issue

**Comment by fb64** [comment]
Here the new PR : https://github.com/langchain4j/langchain4j/pull/2184,  may you can close this one.

**Comment by langchain4j** [comment]
@fb64 thanks!

**Pull request closed without merging**
