### PR TITLE
Experimental: RAG: SQL database content retriever

### PR DESCRIPTION
**Pull request by ghost**
## Issue
https://github.com/langchain4j/langchain4j/issues/232

## Change
An experimental `SqlDatabaseContentRetriever` has been added.

Simplest usage example:
```java
ContentRetriever contentRetriever = SqlDatabaseContentRetriever.builder()
    .dataSource(dataSource)
    .chatLanguageModel(openAiChatModel)
    .build();
```
In this case SQL dialect and table structure will be determined from the `DataSource`.

But it can be customized:
```java
ContentRetriever contentRetriever = SqlDatabaseContentRetriever.builder()
    .dataSource(dataSource)
    .sqlDialect("PostgreSQL")
    .databaseStructure(...)
    .promptTemplate(...)
    .chatLanguageModel(openAiChatModel)
    .maxRetries(2)
    .build();
```

See `SqlDatabaseContentRetrieverIT` for a full example.

## General checklist

- [X] There are no breaking changes
- [X] I have added unit and integration tests for my change
- [X] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [X] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)

## Checklist for adding new model integration

- [X] I have added my new module in the [BOM](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-bom/pom.xml)

### CODE REVIEW

**Comment by langchain4j** [comment]
cc @dandreadis @geoand

**Comment by geoand** [comment]
Also cc @jmartisk

**Comment by jmartisk** [comment]
Looks cool, we have something like it in the Quarkus samples, but this looks more general
Did you try with various models? I remember trying to use codellama and mistral for the sample that we have, but it just didn't work properly (only GPT produced reasonable queries).

**Comment by langchain4j** [comment]
@jmartisk yes, I played with `gpt-3.5-turbo`, `open-mistral-7b` (via Mistral API) and `tinydolphin` (via Ollama).
For those integration  tests that I have, `gpt-3.5-turbo` works most of the time, `open-mistral-7b` in like 70% cases and `tinydolphin` only with simple cases. I can imagine it will work much better with https://ollama.com/library/sqlcoder or other text-to-SQL models.

**Pull request merged**
