### PR TITLE
feat: Qdrant Embedding Removal

### LINKED ISSUE #2178: [FEATURE] Support removing embedding from Qdrant EmbeddingStore
I am working on implementing a chat platform that provides access to internal company knowledge by using RAG.
I would like to use Qdrant as vector database for the EmbeddingStore, but in order to be able to update documents that are ingested into the EmbeddingStore, I need to be able to delete the old embedding.

Unfortunately, this is not implemented at the moment, instead one receives a `UnsupportedOperationException` "not supported yet" when calling any of the remove or removeAll methods.

I can implement this myself, just created this issue as requested by your CONTRIBUTING,

### PR DESCRIPTION
**Pull request by florian-h05**
Closes #2178.

This implements the remove methods of the `EmbeddingStore` for Qdrant.
It also addresses a few Sonarlint warnings for `QdrantEmbeddingStore`.

Integration tests have been added.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
@florian-h05 thanks a lot!

**Comment by florian-h05** [comment]
Thank you for the quick review and the awesome LangChain4j project!!

**Comment by langchain4j** [comment]
@florian-h05 easy and clean PR == fast review and merge :)

**Comment by florian-h05** [comment]
@langchain4j Are there any plans when the next release will be published?

**Comment by langchain4j** [comment]
@florian-h05 this week, most probably Thu or Fri

**Pull request merged**
