### PR TITLE
Bump latest version of Docusaurus

### PR DESCRIPTION
**Pull request by agoncal**
Well, well, I'm not a front-end guy and therefore not super confortable with NPM and Node. 

I've updated Docusaurus so it runs the latest version and to see if I can add search and single-page to the documentation.

Hope this runs on CI/CD

Also see https://github.com/langchain4j/langchain4j/pull/1221

### CODE REVIEW

**Comment by LizeRaes** [comment]
Thanks a lot! In case there are issues with the CI/CD, @amithkoujalgi (ollama4j maintainer) did an amazing job last time with setting up the docusaurus and getting everything deployed <3 He may be able to help if needed

**Comment by agoncal** [comment]
@LizeRaes looks like the build has passed. Would you accept the PR then or shall we wait for @amithkoujalgi to have a look at it ?

**Review by LizeRaes — APPROVED** [review]

**Comment by amithkoujalgi** [comment]
@agoncal @LizeRaes I've been occupied with other stuff and I've not been able to look into this. Apologies for the delay in response from my end.

**Comment by LizeRaes** [comment]
This should be fine, thanks @agoncal!

**Pull request merged**
