### PR TITLE
Migrate Ollama from gson to jackson

### LINKED ISSUE #1688: Ollama: migrate from Gson to Jackson
Apart from Gson being used in `OllamaApiIT`, `OllamaMessagesUtils` uses `Json.toJson()` method that use Gson under the hood

### PR DESCRIPTION
**Pull request by Martin7-1**
## Issue

Closes #1688 

## Change

1. Replace explicit use of `Gson` to `Jackson` in `OllamaApiIT`

> `OllamaMessageUtils` use `Json.toJson` method, we can change the default implementation like this [discuss](https://github.com/langchain4j/langchain4j/issues/1688#issuecomment-2327810439) . In this way we don't need to change the code in `OllamaMessageUtils`

## General checklist

- [x] There are no breaking changes
- [ ] I have added unit and integration tests for my change
- [x] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [x] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for adding new model integration

- [ ] I have added my new module in the [BOM](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-bom/pom.xml)

## Checklist for adding new embedding store integration

- [ ] I have added a `{NameOfIntegration}EmbeddingStoreIT` that extends from either `EmbeddingStoreIT` or `EmbeddingStoreWithFilteringIT`
- [ ] I have added my new module in the [BOM](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-bom/pom.xml)

## Checklist for changing existing embedding store integration

- [ ] I have manually verified that the `{NameOfIntegration}EmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

### CODE REVIEW

**Comment by Martin7-1** [comment]
@langchain4j Hi! All tests can pass in my local environment. Could you please check again? You can merge it before #1658

**Comment by langchain4j** [comment]
@Martin7-1 this PR is still in progress, right? AFAIU `OllamaMessageUtils` changes are still pending

**Comment by Martin7-1** [comment]
@langchain4j My bad. I forgot it. Now is ready to review.

**Review by ghost — APPROVED** [review]
@Martin7-1 thank you, good job!

**Pull request merged**
