### PR TITLE
Added ChatModelListener in anthropic model

### PR DESCRIPTION
**Pull request by Claudio-code**
## Issue

Closes #

Issue https://github.com/langchain4j/langchain4j/issues/1757

## General checklist

- [x] There are no breaking changes
- [x] I have added unit and integration tests for my change
- [x] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [ ] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for adding new model integration

- [ ] I have added my new module in the [BOM](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-bom/pom.xml)

## Checklist for adding new embedding store integration

- [ ] I have added a `{NameOfIntegration}EmbeddingStoreIT` that extends from either `EmbeddingStoreIT` or `EmbeddingStoreWithFilteringIT`
- [ ] I have added my new module in the [BOM](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-bom/pom.xml)

## Checklist for changing existing embedding store integration

- [ ] I have manually verified that the `{NameOfIntegration}EmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

### CODE REVIEW

**Comment by Claudio-code** [comment]
The only error I got is in the Claude 1.2 model which also happens in the master

Screenshot from 2024-09-17 21-03-34

**Comment by langchain4j** [comment]
@Claudio-code please take a look at `ChatModelListenerIT` and `StreamingChatModelListenerIT` and extend them, the same way as `OpenAiChatModelListenerIT` and `OpenAiStreamingChatModelListenerIT`

**Comment by Claudio-code** [comment]
@langchain4j  Added tests to listener in both classes

**Review by ghost — APPROVED** [review]
@Claudio-code thank you!

**Pull request merged**
