### PR TITLE
Remove Java 17 from nightly workflow

### PR DESCRIPTION
**Pull request by kpavlov**
I feel, that nightnly build fails due to lack of resources...

## Issue
Nightly build fails when it runs matrix build for 2 JDKs. 
Trying to address it by removing Java 17 from the matrix configuration in the nightly workflow YAML file and running only on current LTS java version.

## Change
Remove Java 17 from nightly workflow

Java 17 has been definitively removed from the matrix configuration in the nightly workflow YAML file. This change restricts the build and testing process to only Java 21, aligning with our current Java version requirements.

## General checklist

- [x] There are no breaking changes
- [ ] I have added unit and integration tests for my change
- [ ] I have manually run all the unit and integration tests in the module I have added/changed, and they are all green
- [ ] I have manually run all the unit and integration tests in the [core](https://github.com/langchain4j/langchain4j/tree/main/langchain4j-core) and [main](https://github.com/langchain4j/langchain4j/tree/main/langchain4j) modules, and they are all green

- [ ] I have added/updated the [documentation](https://github.com/langchain4j/langchain4j/tree/main/docs/docs)
- [ ] I have added an example in the [examples repo](https://github.com/langchain4j/langchain4j-examples) (only for "big" features)
- [ ] I have added/updated [Spring Boot starter(s)](https://github.com/langchain4j/langchain4j-spring) (if applicable)

## Checklist for adding new maven module

- [ ] I have added my new module in the root `pom.xml` and `langchain4j-bom/pom.xml`

## Checklist for adding new embedding store integration

- [ ] I have added a `{NameOfIntegration}EmbeddingStoreIT` that extends from either `EmbeddingStoreIT` or `EmbeddingStoreWithFilteringIT`
- [ ] I have added a `{NameOfIntegration}EmbeddingStoreRemovalIT` that extends from `EmbeddingStoreWithRemovalIT`

## Checklist for changing existing embedding store integration

- [ ] I have manually verified that the `{NameOfIntegration}EmbeddingStore` works correctly with the data persisted using the latest released version of LangChain4j

### CODE REVIEW

**Comment by langchain4j** [comment]
Hi @kpavlov, thank you!

Since we target Java 17, it would be great to keep it. What about splitting the nightly build into 2 separate workflows?

**Comment by kpavlov** [comment]
If we run on 17, then tests for jlama will not run, since jlama [requires 21+](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-jlama/pom.xml#L21)

**Comment by langchain4j** [comment]
> If we run on 17, then tests for jlama will not run, since jlama [requires 21+](https://github.com/langchain4j/langchain4j/blob/main/langchain4j-jlama/pom.xml#L21)

I meant that we can run both 17 and 21, but in 2 separate workflows, to avoid resource exhaustion

**Comment by kpavlov** [comment]
Then we should not run them in parallel to avoid hitting rate limits. Maybe we can run single workflow in a different schedule with target JDK as a param?

**Comment by kpavlov** [comment]
@langchain4j , please feel free to close this PR if it doesn't seems right

**Comment by langchain4j** [comment]
> Then we should not run them in parallel to avoid hitting rate limits. Maybe we can run single workflow in a different schedule with target JDK as a param?

Yes, makes sense. We can schedule 17 for 00:00 and 21 for 04:00

**Pull request closed without merging**
